import { getConceptModelForLearningUnit } from "../content/conceptModels.js";

export const LEARNING_FLOW_STAGES = Object.freeze({
  UNDERSTAND: "understand",
  PRACTICE: "practice",
  VERIFY: "verify",
});

function flowDefinition(definition) {
  return Object.freeze({
    ...definition,
    conceptModel: getConceptModelForLearningUnit(definition.learningUnitId),
    stageHints: Object.freeze(definition.stageHints),
  });
}

const FLOW_DEFINITIONS = Object.freeze({
  "component-jsx-pure-render": flowDefinition({
    learningUnitId: "component-jsx-pure-render",
    version: 1,
    objective: "把函数组件理解为从当前输入计算 UI 描述的纯 render，并区分组件函数执行、JSX 描述与后续 DOM commit。",
    aiReviewTarget: "只检查本节核心目标：学习者应能说明函数组件在 render 中读取当前 props/state/context 并返回 JSX 描述；相同输入的 render 计算应保持纯净和可重复；组件函数执行不等于 DOM 已提交变化；不要把 render/commit 内部调度细节或 Strict Mode 实现机制当成本节必答项。",
    coreModelTitle: "Inputs → Component Function → JSX Description → Commit",
    mentalModel: "组件函数首先是 UI 计算：读取本次 render 的输入并返回 React 元素描述。React 可以重复执行这段计算，因此 render 不能修改组件外部已经存在的数据；DOM 变化属于后续 commit，而不是组件函数自己直接完成。",
    misconceptionTitle: "不要把 render 当成“执行一次就改一次 DOM”",
    misconception: "“组件函数运行就等于 DOM 更新”“开发期重复调用说明 React 有 bug”“render 里任何 mutation 都禁止”都会把纯计算、外部副作用和 commit 混在一起。",
    decisionRuleTitle: "副作用先离开 render",
    decisionRule: "只要逻辑会修改 render 开始前已经存在、可被外部观察的数据，就不要放在组件函数主体里；事件触发的动作放 Event Handler，需要持续外部同步的逻辑再考虑 Effect。",
    practiceTitle: "先预测相同输入的结果，再修掉 render 中的外部 mutation",
    practiceDescription: "先观察纯/非纯计算在相同输入下是否稳定，再把同一个 purity mental model 迁移到一段新的组件代码。",
    verifyTitle: "离开 Demo，判断哪些代码仍然是纯 UI 计算",
    verifyDescription: "诊断题会检查 JSX、组件执行、外部 mutation 与 commit 的边界，并用陌生代码测试迁移。",
    stageHints: {
      understand: "先区分 render 输入、组件函数、JSX 描述和 commit。",
      practice: "用重复计算实验验证 purity，再修复一段 render-time 外部 mutation。",
      verify: "离开当前示例，判断陌生组件代码是否仍能安全重复执行。",
    },
  }),
  "props": flowDefinition({
    learningUnitId: "props",
    version: 1,
    objective: "理解 Props 是父级给当前 render 的只读输入，并用默认参数与派生计算保持单向数据流。",
    aiReviewTarget: "只检查本节核心目标：学习者应能说明 props 由上层所有者提供、子组件只读取当前输入；JavaScript 解构默认值只在 undefined 时生效；能由当前 props/state 推导的值应直接计算而不是复制成额外 State。不要把 memoization 或复杂状态管理当成本节必答项。",
    coreModelTitle: "Owner State → Props Input → Derivation → Child JSX",
    mentalModel: "数据由上层所有者更新，子组件在每次 render 中读取当前 props。Props 不是子组件可变存储；缺省值通过普通 JavaScript 参数语义处理，能够从 props 直接得到的显示值应在 render 中派生。",
    misconceptionTitle: "Props 不是子组件自己的可变 State",
    misconception: "“子组件可以直接改 props”“default 会替换所有 falsy 值”“actualPrice 这种计算值必须再存 State”都会制造错误的数据所有权或同步路径。",
    decisionRuleTitle: "先找单一数据源，再决定是否需要 State",
    decisionRule: "如果值由父级输入决定，就把源数据留在拥有者并通过 props 传递；如果当前值可从这些输入计算出来，直接派生，不要复制一份需要同步的 State。",
    practiceTitle: "从父级输入一路追到子组件显示结果",
    practiceDescription: "先修改父级控制面板观察 Props 更新，再修复一段把派生价格错误复制为 State 的代码。",
    verifyTitle: "检查默认值、只读输入与派生计算有没有混淆",
    verifyDescription: "诊断题包含陌生组件代码，要求根据所有权和当前 render 输入做判断。",
    stageHints: {
      understand: "先建立数据所有者 → Props → 子组件派生值的单向链路。",
      practice: "观察父级 State 改变如何形成新 Props，再移除重复派生 State。",
      verify: "离开 Demo，根据陌生代码判断 Props 所有权、默认值和派生值。",
    },
  }),
  "children": flowDefinition({
    learningUnitId: "children",
    version: 1,
    objective: "用 children composition 把调用者拥有的业务内容与容器拥有的布局/交互外壳解耦。",
    aiReviewTarget: "只检查本节核心目标：学习者应能说明 children 是调用位置传入的 React node；调用者拥有具体业务内容和结构，容器只负责自身布局/视觉/明确交互；composition 与稳定语义 props 可以同时存在。不要把 Context、render props 或组件库高级 slot API 当成本节必答项。",
    coreModelTitle: "Caller Structure → children → Reusable Shell",
    mentalModel: "当内部结构需要由调用者决定时，调用者直接组装 JSX 并通过 children 交给容器。容器只实现它真正拥有的外壳职责，不需要知道内容里的业务字段。",
    misconceptionTitle: "children 不是 HTML 字符串，也不是“容器接管业务”",
    misconception: "把 children 当字符串模板、让容器根据大量 type/boolean props 猜业务内容，或者认为用了 composition 就不能再有普通 props，都会模糊职责边界。",
    decisionRuleTitle: "结构变化交给组合，稳定语义保留显式 Props",
    decisionRule: "内部结构差异大且由调用者知道时优先 children/slot；如果差异只是 title、size、tone 等少量稳定语义，继续使用显式 props 更清楚。",
    practiceTitle: "先观察同一外壳承载不同结构，再修掉 type 分支",
    practiceDescription: "用 CardContainer / ModalLayout 看清职责边界，再把一个根据 contentType 内置业务分支的容器改成 composition。",
    verifyTitle: "判断一段结构变化应该放在调用者还是容器",
    verifyDescription: "诊断题会检查 children 的数据形态、职责所有权和 composition / props 边界。",
    stageHints: {
      understand: "先区分调用者拥有的内容结构与容器拥有的外壳。",
      practice: "比较文本、表单共用同一容器，再把陌生代码改为 children composition。",
      verify: "离开当前示例，根据职责边界决定结构应该由谁提供。",
    },
  }),
  "multi-slots": flowDefinition({
    learningUnitId: "multi-slots",
    version: 1,
    objective: "设计具名插槽的明确三态协议：undefined 使用默认、React node 覆盖、false 显式隐藏。",
    aiReviewTarget: "只检查本节核心目标：学习者应能区分 slot prop 的 undefined、调用者自定义值与 false 三种语义；理解简单的 || fallback 会把 false 与 undefined 压扁；具名 slot 仍然只是显式 props 中的 React node。不要把 headless UI 框架或复杂 compound component 模式当成本节必答项。",
    coreModelTitle: "undefined → default / node → override / false → hide",
    mentalModel: "生产级 slot API 不能只看 truthy/falsy。未传值表示接受默认模板，自定义 React node 表示覆盖，false 表示调用者明确要求这个区域不存在。",
    misconceptionTitle: "不要用 falsy 判断吃掉“显式隐藏”",
    misconception: "footer || <DefaultFooter /> 会把 footer=false 误判成需要默认值，从而破坏三态 API 的业务语义。",
    decisionRuleTitle: "先冻结 slot 协议，再写条件渲染",
    decisionRule: "如果组件承诺 default / override / hide 三种状态，就分别判断 false、undefined 和其他值；不要让 JavaScript 的宽泛 falsy 规则替代 API contract。",
    practiceTitle: "先走四种 Modal 场景，再修复错误 fallback",
    practiceDescription: "观察默认、局部覆盖和显式隐藏的差异，再修复一段用 || 实现 footer slot 的代码。",
    verifyTitle: "用陌生 slot 代码检查三态语义是否被保留",
    verifyDescription: "诊断题会区分 undefined、false、自定义 node 与 Context 等相邻概念。",
    stageHints: {
      understand: "先建立 default / override / hide 三态协议。",
      practice: "对比四种 Modal，再修复会吞掉 false 的 fallback。",
      verify: "离开 Demo，根据 API contract 判断陌生 slot 实现。",
    },
  }),
  "conditional-rendering": flowDefinition({
    learningUnitId: "conditional-rendering",
    version: 1,
    objective: "先用可靠的业务状态模型表达当前情境，再用普通 JavaScript 控制流把它映射为唯一清晰的 UI 分支。",
    aiReviewTarget: "只检查本节核心目标：学习者应能说明 React 条件渲染使用普通 JavaScript；状态建模先于 if/ternary/&& 语法选择；互斥状态不应由可产生非法组合的松散 booleans 表达；能派生的条件不应复制为 State；&& 左操作数不是自动 boolean。不要把状态机库实现当成本节必答项。",
    coreModelTitle: "Business State → Branch Priority → JSX",
    mentalModel: "条件渲染的核心不是记三种语法，而是保证当前业务事实能可靠映射到一个 UI 分支。阻断态可以 early return，小型二选一可以 ternary，真正 boolean 的可选片段适合 &&。",
    misconceptionTitle: "语法不会修复错误的状态模型",
    misconception: "多个松散 boolean 即使写成漂亮 JSX 也可能组成矛盾 UI；count && JSX 也可能把 0 渲染出来。",
    decisionRuleTitle: "先建模互斥关系，再选最简单控制流",
    decisionRule: "互斥情境优先使用一个明确 status；能由现有 State 推导的 isEmpty/isTerminal 直接计算；控制流只负责表达已经正确建模的业务事实。",
    practiceTitle: "先切换四态，再移除一份重复状态",
    practiceDescription: "观察 loading/error/empty/success 的分支，然后把陌生列表组件中的 isEmpty 复制 State 改成 render-time 派生。",
    verifyTitle: "判断陌生 UI 分支的问题来自语法还是状态建模",
    verifyDescription: "诊断题覆盖 early return、&& 的 0、互斥状态与派生条件。",
    stageHints: {
      understand: "先区分业务状态、分支优先级和 JSX 语法。",
      practice: "遍历四态，再修掉重复 isEmpty State。",
      verify: "离开 Demo，根据状态模型判断陌生条件渲染代码。",
    },
  }),
  "rendering-lists-key": flowDefinition({
    learningUnitId: "rendering-lists-key",
    version: 1,
    objective: "解释为什么稳定 key 决定组件身份与局部 State 归属，而不只是列表渲染性能。",
    aiReviewTarget: "只检查本节核心目标：学习者应能说明 stable key 是同级元素的稳定身份线索；reorder 时 React 是否匹配到同一组件身份决定 local State 是否继续属于同一业务实体；Props 更新、DOM 更新与 local State 保留不是同一件事。不要把 reconciliation 内部实现、极端边界或性能细节当成本节必答项。",
    coreModelTitle: "key → Component Identity → State preservation",
    mentalModel: "同一父节点下，React 需要判断前后两次 render 中“哪个组件还是同一个组件”。稳定 key 提供身份线索；身份延续时，局部 State 才能继续属于正确的业务实体。",
    misconceptionTitle: "不只是性能优化",
    misconception: "“key 主要是为了性能或消除 warning。”——真正危险的是不稳定身份会让已有局部 State 被复用到错误的数据实体。",
    decisionRuleTitle: "什么时候必须稳定 key",
    decisionRule: "如果列表会 insert / delete / reorder，或列表项包含输入、展开、动画等局部 State，优先使用来自数据模型、在实体生命周期内保持稳定的 id。",
    practiceTitle: "先做判断，再让 Demo 证明或推翻它",
    practiceDescription: "先预测结果，再亲手操作真实 Demo，最后把同一个 identity mental model 迁移到新场景。",
    verifyTitle: "不看答案，检查你有没有把几个身份机制混在一起",
    verifyDescription: "诊断题会区分“记住 stable id 规则”和“能解释 identity / Props / State / DOM 的因果关系”。答错时先用反证实验纠正模型，再看完整解释。",
    stageHints: {
      understand: "先建立 key → identity → State preservation 的关系。",
      practice: "先预测，再用真实 Demo 验证 index key 与 stable id 的差异。",
      verify: "离开当前解释，用诊断题检查你是否真正区分了 identity、Props、State 与 DOM。",
    },
  }),
  "prop-drilling": flowDefinition({
    learningUnitId: "prop-drilling",
    version: 1,
    objective: "根据数据所有权、真正消费者和组件职责，在显式 Props、Composition 与 Context 之间做边界判断。",
    aiReviewTarget: "只检查本节核心目标：学习者应能说明 props drilling 不是按层数自动判错；显式 props 适合局部清晰依赖；布局中间层可用 composition 接收已组装 JSX；Context 适合多个远距离消费者共享环境式依赖，同时会让依赖更隐式并建立订阅。不要把外部 store 或 Context 性能微优化当成本节必答项。",
    coreModelTitle: "Ownership + Consumers → Props / Composition / Context",
    mentalModel: "先问数据归谁、真正消费者是谁，再选择传递方式。Props 最显式；中间层只是布局时可以通过 composition 绕过业务数据；多个远距离消费者共享同一环境值时再考虑 Context。",
    misconceptionTitle: "不要把 Context 当成“少写 Props”的默认答案",
    misconception: "两三层 Props 完全可能合理；过早 Context 会隐藏依赖来源，而 composition 也不会改变数据真正的所有者。",
    decisionRuleTitle: "先优化职责边界，再优化传递路径",
    decisionRule: "依赖局部且清楚就保留 props；布局层不需要理解数据时让父级直接组合 JSX；真正跨层、多消费者的共享依赖再用 Context。",
    practiceTitle: "比较三条路径，再重构一个只负责布局的中间层",
    practiceDescription: "修改同一 user 观察三条路径都能工作，然后选择能去掉机械透传、又不过早引入 Context 的最小修复。",
    verifyTitle: "根据消费范围判断传递机制，而不是数组件层数",
    verifyDescription: "诊断题用陌生组件树检查显式依赖、composition、Context 与 State ownership。",
    stageHints: {
      understand: "先看数据所有者、真实消费者和中间层职责。",
      practice: "比较 Props / Composition / Context，再修复一条布局型透传链。",
      verify: "离开 Demo，根据消费范围选择最合适的数据路径。",
    },
  }),
  "state-snapshot-queue": flowDefinition({
    learningUnitId: "state-snapshot-queue",
    version: 1,
    objective: "解释为什么 setter 不会改写当前 render 的 State snapshot，以及 replace update 与 updater function 如何按队列顺序计算下一份 State。",
    aiReviewTarget: "只检查本节核心目标：学习者应能区分 current render snapshot、replace update、updater function 与 queue processing；理解 setter 不会回头改写当前 handler 的 snapshot，updater 会消费前一项 pending State，queue 按入队顺序得到 next render State。不要把调度 lane、React 内部数据结构或并发实现细节当成本节必答项。",
    coreModelTitle: "Render Snapshot → Update Queue → Next Render State",
    mentalModel: "每次 render 都拿到一份固定 State snapshot。setter 不会回头修改这份 snapshot；它把 replace value 或 updater function 加入队列。React 随后按顺序处理队列，得到下一次 render 的 State。",
    misconceptionTitle: "不要只背“setState 是异步的”",
    misconception: "“调用 setter 后变量应该立刻变”“连续调用三次就会自动累加三次”“batching 只保留最后一次调用”都混淆了 current snapshot 与 pending update queue。",
    decisionRuleTitle: "什么时候用 updater function",
    decisionRule: "如果下一份 State 依赖同一批更新里前一项计算出的 pending State，就使用 updater function；如果你要用当前 render 已知信息直接替换成一个具体值，replace update 更直接。",
    practiceTitle: "先预测数字，再解释队列为什么得到这个数字",
    practiceDescription: "不要只看最终 count。先预测每个 scenario 的 queue，再用 Queue Debugger 对照 handler snapshot、每一步 pending State 与 next render state。",
    verifyTitle: "不看 Demo，独立推演一次 update queue",
    verifyDescription: "诊断题会检查你是否真正区分 snapshot、replace、updater 与 queue order。答错时先用现有 Queue Debugger 反证自己的模型，再重新选择。",
    stageHints: {
      understand: "先区分 current snapshot、update request、queue processing 与 next render state。",
      practice: "先预测 Replace / Updater / mixed queue，再用 Queue Debugger 逐步验证。",
      verify: "离开当前日志，独立推演 queue，并诊断是否仍把 setter 当成同步变量赋值。",
    },
  }),
  "preserving-resetting-state": flowDefinition({
    learningUnitId: "preserving-resetting-state",
    version: 1,
    objective: "根据产品业务身份决定局部 State 应该保留还是重置，并把 key 放在准确的 identity boundary。",
    coreModelTitle: "Identity match → Preserve State / New identity → Reset State",
    mentalModel: "React 是否保留 local State，取决于前后 render 能否匹配到同一个组件身份，而不是某个 prop 值是否变化。同一父级位置、组件类型与 key 身份仍匹配时，State 会保留；身份不再匹配时，新组件从初始 State 开始。",
    misconceptionTitle: "不要把 key 当成“强制刷新”",
    misconception: "真正要解决的是产品身份边界：哪些 UI 仍代表同一个实例，哪些 UI 因业务实体切换应该成为新实例。把 key 放得过高或使用随机 key，都会重置本来应该保留的 State。",
    decisionRuleTitle: "先划业务 State 边界，再决定 key 放哪里",
    decisionRule: "如果某段局部 State 只属于当前业务实体，并且实体切换时明确应该丢弃，就让稳定业务 id 参与这段子树的身份；如果外层 UI State 应跨实体保留，就不要把 identity reset 扩大到外层。",
    practiceTitle: "先判断该保留哪一层，再选择最小 identity 修复",
    practiceDescription: "先用 Chat Demo 对比“只变 Props”和“改变业务 key”，再把模型迁移到 WorkspaceShell / InvoiceEditor：只 reset 真正属于新 customer 的编辑器 State。",
    verifyTitle: "不背 key 技巧，检查你能否划出正确的 identity boundary",
    verifyDescription: "诊断题会检查 Props、component identity、local State、key 和业务实体之间的关系，以及 reset 边界应该放在哪一层。答错时先用现有 Demo 做反证，再重新判断。",
    stageHints: {
      understand: "先区分业务实体、Props 输入、React component identity 与 local State。",
      practice: "先验证同一 Chat identity 如何保留 draft，再选择只 reset 必要子树的 patch。",
      verify: "离开当前示例，根据产品 State 边界判断什么时候保留 identity、什么时候创建新 identity。",
    },
  }),
  "not-need-effect": flowDefinition({
    learningUnitId: "not-need-effect",
    version: 1,
    objective: "根据逻辑的因果来源判断它应该留在 render、Event Handler、Effect，还是用 identity reset 表达业务边界。",
    coreModelTitle: "Why it runs → Where it belongs",
    mentalModel: "先问“为什么这段逻辑需要运行？”：为当前 UI 计算值就留在 render；因为一次明确用户交互就留在 Event Handler；因为组件存在而需要与 React 外部系统保持同步，才使用 Effect。",
    misconceptionTitle: "Effect 不是通用“变化监听器”",
    misconception: "“有副作用就用 Effect”“依赖某个 State 就监听它”“请求都必须放 Effect”都忽略了真正的因果来源。Effect 主要负责外部同步，而不是把内部数据流重新接一遍。",
    decisionRuleTitle: "先找因果，再谈 API",
    decisionRule: "能从当前 props/state 派生就直接计算；明确由用户动作触发就放 handler；需要组件生命周期内维持外部同步才用 Effect。key reset 与 memoization 分别属于 identity 与 performance 决策，不是 Effect 的通用替代或变体。",
    practiceTitle: "先判断因果来源，再让三个 Demo 场景验证边界",
    practiceDescription: "不要从 API 名称出发。先判断这段逻辑为什么运行，再对照派生列表、购买事件和 userId identity reset，最后迁移到真正的外部订阅场景。",
    verifyTitle: "不看口诀，按因果来源做工程判断",
    verifyDescription: "诊断题会检查你是否能区分 render derivation、event-caused logic、external synchronization、identity reset 与 memoization。答错时先用现有 Demo 反证，再重新选择并复述。",
    stageHints: {
      understand: "先建立 render / Event Handler / Effect / identity reset 的因果边界。",
      practice: "先判断 filteredProducts、购买日志与 userId reset 为什么运行，再用 Demo 验证。",
      verify: "离开当前说明，根据因果来源独立判断代码应该放在哪里。",
    },
  }),
  "lifecycle-of-reactive-effects": flowDefinition({
    learningUnitId: "lifecycle-of-reactive-effects",
    version: 1,
    objective: "把 Effect 理解为独立外部同步过程，并根据真实 reactive reads 判断何时 cleanup 旧同步、setup 新同步。",
    coreModelTitle: "Render → Commit → Cleanup(old) → Setup(new)",
    mentalModel: "Effect 不等同于组件生命周期回调。render 先读取本次 reactive values，commit 后如果同步目标需要变化，React 先运行上一轮 cleanup 撤销旧外部关系，再用本次 committed values 运行 setup 建立下一轮同步。",
    misconceptionTitle: "依赖数组不是“运行次数控制器”",
    misconception: "真正的问题是 setup 读取了哪些 reactive values、这些值是否决定同步关系。为了少运行删除真实依赖会制造 stale synchronization；反过来，组件里某个值会变化也不代表它一定要让这个 Effect 重建。",
    decisionRuleTitle: "先定义同步目标，再检查 reactive reads",
    decisionRule: "决定外部同步目标的 reactive value 必须保留为依赖；如果某个 read 只是为了基于旧 State 计算下一份 State，可改用 functional updater；如果它属于 Effect 内触发、但不应重建同步的事件逻辑，可用 Effect Event 分离。先改变代码，再让依赖准确反映代码。",
    practiceTitle: "先观察真实 cleanup/setup，再重建一次完整更新顺序",
    practiceDescription: "用聊天室 Demo 验证 roomId 变化、静音切换和消息更新的不同效果，再通过 ordered-sequence 把 update → render → commit → cleanup → setup 顺序迁移到 topic subscription。",
    verifyTitle: "不靠依赖数组口诀，判断同步过程为什么需要重建",
    verifyDescription: "诊断题会检查 cleanup 时机、真实依赖、functional updater、Effect Event 与 Strict Mode 边界。答错时先用日志或源码做反证，再重新选择并复述。",
    stageHints: {
      understand: "先区分 render/commit 与 Effect 的 cleanup/setup，并找到真正决定外部同步目标的值。",
      practice: "切换 room、静音和消息更新，观察哪些变化真的重建连接，再排列订阅更新顺序。",
      verify: "离开当前日志，根据同步目标和 reactive reads 独立判断依赖与生命周期。",
    },
  }),
});

export const SINGLE_LEARNING_FLOW_UNIT_IDS = Object.freeze(Object.keys(FLOW_DEFINITIONS));
 
export function getSingleLearningFlowDefinition(learningUnitId) {
  return FLOW_DEFINITIONS[learningUnitId] ?? null;
}

export function isSingleLearningFlowUnit(learningUnitId) {
  return Boolean(getSingleLearningFlowDefinition(learningUnitId));
}
