import { RAW_NOTE_LOADERS } from "virtual:raw-mdx-note-registry";

export const NOTE_CONTENT_ROOT = "src/content/notes";
export const NOTE_FILE_SUFFIX = ".mdx";
export const NOTE_PATH_PATTERN = `${NOTE_CONTENT_ROOT}/{learningUnitId}${NOTE_FILE_SUFFIX}`;

const NOTE_MODULE_LOADERS = import.meta.glob("../content/notes/*.mdx");
const NOTE_IMPORT_ROOT = "../content/notes";

function assertLearningUnitId(learningUnitId) {
  if (typeof learningUnitId !== "string" || !/^[a-z0-9][a-z0-9-]*$/.test(learningUnitId)) {
    throw new TypeError(`Invalid learning unit id: ${String(learningUnitId)}`);
  }
  return learningUnitId;
}

export function getNoteFileName(learningUnitId) {
  return `${assertLearningUnitId(learningUnitId)}${NOTE_FILE_SUFFIX}`;
}

export function getNotePath(learningUnitId) {
  return `${NOTE_CONTENT_ROOT}/${getNoteFileName(learningUnitId)}`;
}

function getNoteImportPath(learningUnitId) {
  return `${NOTE_IMPORT_ROOT}/${getNoteFileName(learningUnitId)}`;
}

/**
 * Stable consumer API for Demo -> Note resolution.
 *
 * Vite expands the glob into per-file dynamic import functions. No note module
 * is eagerly imported, so adding many notes does not grow the initial app
 * bundle with their compiled MDX bodies.
 *
 * Missing notes are represented by null and are a normal migration state while
 * content is being added incrementally.
 *
 * @param {string} learningUnitId
 * @returns {null | (() => Promise<unknown>)}
 */
export function getNoteLoader(learningUnitId) {
  const importPath = getNoteImportPath(learningUnitId);
  return NOTE_MODULE_LOADERS[importPath] ?? null;
}

/**
 * Resolve the original MDX source for consumers that need deterministic text
 * rather than the compiled React component (for example the AI context layer).
 *
 * Raw-note modules are generated by a Vite virtual-module plugin so they never
 * pass through the MDX compiler. Each note still loads lazily as its own chunk.
 *
 * @param {string} learningUnitId
 * @returns {null | (() => Promise<string>)}
 */
export function getRawNoteLoader(learningUnitId) {
  const noteId = assertLearningUnitId(learningUnitId);
  return RAW_NOTE_LOADERS[noteId] ?? null;
}

/**
 * Load raw MDX text while treating a missing note as a normal, non-fatal state.
 *
 * @param {string} learningUnitId
 * @returns {Promise<string | null>}
 */
export async function loadRawNote(learningUnitId) {
  const loader = getRawNoteLoader(learningUnitId);
  if (!loader) return null;

  const rawNote = await loader();
  if (typeof rawNote !== "string") {
    throw new TypeError(`Raw note ${learningUnitId} did not resolve to text`);
  }
  return rawNote;
}

export function hasNote(learningUnitId) {
  return getNoteLoader(learningUnitId) !== null;
}

export function getAvailableNoteIds() {
  const prefix = `${NOTE_IMPORT_ROOT}/`;
  return Object.keys(NOTE_MODULE_LOADERS)
    .filter((path) => path.startsWith(prefix) && path.endsWith(NOTE_FILE_SUFFIX))
    .map((path) => path.slice(prefix.length, -NOTE_FILE_SUFFIX.length))
    .sort();
}
