const LISTS_KEY_MODEL = {
  learningUnitId: "rendering-lists-key",
  version: 1,
  mechanismTitle: "先把这些对象分开，再讨论 key",
  mechanismAriaLabel: "Lists and Key 机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它负责什么",
    change: "reorder 时会怎样",
  },
  contrastTitle: "三种变化，不要混成同一种“复用 / 重建”",
  mechanismMap: [
    {
      id: "business-entity",
      label: "业务实体",
      example: "task",
      role: "产品里真正要持续识别的对象。",
      reorder: "顺序会变，但同一个 task 仍是同一个业务实体。",
    },
    {
      id: "key",
      label: "key",
      example: "index / task.id",
      role: "同一父节点下，帮助 React 匹配前后两次 render 中的元素身份。",
      reorder: "index 表示位置；task.id 表示稳定业务身份。",
    },
    {
      id: "props",
      label: "Props",
      example: "task",
      role: "当前 render 传给组件的新输入。",
      reorder: "即使组件身份被复用，Props 仍会更新成当前位置的新 task。",
    },
    {
      id: "component-identity",
      label: "Component Identity",
      example: "EditableRow",
      role: "React 判断“前后是不是同一个组件实例”的结果。",
      reorder: "身份延续时局部 State 会继续属于这个实例。",
    },
    {
      id: "local-state",
      label: "Local State",
      example: "note",
      role: "属于 React 组件身份，而不是业务数据对象或 DOM 节点。",
      reorder: "它跟随被 React 保留的组件身份。",
    },
    {
      id: "dom",
      label: "DOM",
      example: "标题 / input",
      role: "React 根据最新 Props 与 State 提交出来的界面结果。",
      reorder: "节点可能复用或移动，但内容仍可根据新 Props / State 更新。",
    },
  ],
  contrastCases: [
    {
      id: "index-reorder",
      title: "index key + reorder",
      keyStory: "反转前后仍是 0 / 1 / 2，React 更容易按位置延续原身份。",
      identityStory: "位置 0 的 EditableRow 仍被当作原来的组件身份。",
      stateStory: "原来属于位置 0 身份的 note 继续保留。",
      uiStory: "task Props 已经换成新的业务数据，所以标题会更新；note 却可能出现在错误任务旁边。",
      conclusion: "错的不是“DOM 完全没更新”，而是组件身份与业务实体没有正确对齐。",
    },
    {
      id: "stable-reorder",
      title: "stable id + reorder",
      keyStory: "task-a / task-b / task-c 与业务实体绑定，排序改变时 key 本身不变。",
      identityStory: "React 能在新位置认出同一个组件身份。",
      stateStory: "note 随这个身份一起保留，因此跟着 task 移动。",
      uiStory: "这不是 remount；如果真的重建，useState 的 note 应重新初始化。",
      conclusion: "stable key 的价值是该保留身份时保留，而不是“总是重建”。",
    },
    {
      id: "strategy-switch",
      title: "切换 index key ↔ stable id",
      keyStory: "同一行从 key=0 变成 key=task-a（或反过来），显式 key 值本身变了。",
      identityStory: "旧身份无法与新的 key 匹配，因此会创建新的组件身份。",
      stateStory: "新的 EditableRow 从 useState 的初始值重新开始。",
      uiStory: "这才是当前 Demo 中可直接观察的 identity reset / remount 场景。",
      conclusion: "是否重建取决于身份是否还能匹配，而不是“stable id 天生会重建”。",
    },
  ],
  misconceptions: {
    "key-only-warning": {
      id: "key-only-warning",
      title: "把 key 当成 warning / 性能提示",
      diagnosis: "这个判断只看到了语法提示，没有解释 key 为什么会改变局部 State 的归属。",
      counterEvidence: "同一份列表数据只切换 key 策略，就能改变 note 在 reorder 后跟谁走；这已经是可观察的正确性差异。",
      experiment: "先用 index key 给第一行输入 AAA 并反转；再恢复数据，用 stable id 重做一次。只比较 AAA 最后属于哪个 task。",
      evidenceRefs: [{ kind: "source", fileName: "RenderingListsKeyDemo.jsx", startLine: 39, endLine: 46 }],
    },
    "dom-not-updated": {
      id: "dom-not-updated",
      title: "把“组件身份复用”理解成“DOM 没更新”",
      diagnosis: "这里混淆了 React 复用组件身份，与 React 是否提交新的 DOM 内容。",
      counterEvidence: "如果 DOM 内容真的没更新，反转后 AAA 所在行的 task.title / owner 也应该保持旧值；但 Demo 中它们会跟着新的 Props 更新。",
      experiment: "保持 index key：第一行输入 AAA → 反转顺序。只观察 AAA 所在行上方的标题是否变化。",
      evidenceRefs: [
        { kind: "source", fileName: "RenderingListsKeyDemo.jsx", startLine: 22, endLine: 33 },
        { kind: "source", fileName: "RenderingListsKeyDemo.jsx", startLine: 39, endLine: 46 },
      ],
    },
    "state-lives-in-dom": {
      id: "state-lives-in-dom",
      title: "把局部 State 当成 DOM 节点保存的数据",
      diagnosis: "note 来自 EditableRow 的 useState；input 的 value 只是把这个 React State 显示出来。",
      counterEvidence: "如果 note 的来源是 DOM 自己保存的数据，那么源码中的 useState(note) 就无法解释为什么 React 身份变化时 note 会重置。",
      experiment: "先输入 AAA，再切换 index key / stable id 策略。观察 key 值变化导致组件身份重建时，AAA 是否被清空。",
      evidenceRefs: [
        { kind: "source", fileName: "RenderingListsKeyDemo.jsx", startLine: 9, endLine: 11 },
        { kind: "source", fileName: "RenderingListsKeyDemo.jsx", startLine: 29, endLine: 33 },
      ],
    },
    "stable-key-remounts": {
      id: "stable-key-remounts",
      title: "认为 stable id 在 reorder 时会让组件重建",
      diagnosis: "如果 reorder 真的是 remount，useState(\"\") 会重新初始化，原来的 AAA 应该消失。",
      counterEvidence: "stable id 下 AAA 会跟着同一个 task 移到新位置且仍然存在，这恰好证明组件身份被保留。",
      experiment: "切到 stable id → 第一行输入 AAA → 反转顺序。预测 AAA 是消失，还是跟着原 task 移动。",
      evidenceRefs: [
        { kind: "source", fileName: "RenderingListsKeyDemo.jsx", startLine: 9, endLine: 11 },
        { kind: "source", fileName: "RenderingListsKeyDemo.jsx", startLine: 39, endLine: 46 },
      ],
    },
    "id-changes-with-data": {
      id: "id-changes-with-data",
      title: "认为好的 id 应该“跟着数据变化”",
      diagnosis: "稳定 key 的核心恰好相反：同一个业务实体存在期间，它的 key 应保持不变。",
      counterEvidence: "排序改变的是 task 在数组里的位置，不应改变 task.id；index 会随位置语义变化，因此无法代表同一个业务实体。",
      experiment: "反转前后分别看 task-a 的 id 与 index：哪个值仍然描述“这是 task-a”，哪个只描述“它现在排第几”？",
      evidenceRefs: [{ kind: "source", fileName: "RenderingListsKeyDemo.jsx", startLine: 3, endLine: 7 }],
    },
    "props-reset-state": {
      id: "props-reset-state",
      title: "认为 Props 变化会自动重置组件局部 State",
      diagnosis: "Props 是当前 render 的输入；是否保留 local State 取决于组件身份是否延续，而不是某个 prop 是否换了值。",
      counterEvidence: "index key reorder 时 task Props 明明已经换成另一个 task，但 note 仍可能保留在原组件身份上。",
      experiment: "index key 下输入 AAA 后反转：同时观察标题（Props）与 AAA（State），确认它们可以出现不同的变化路径。",
      evidenceRefs: [
        { kind: "source", fileName: "RenderingListsKeyDemo.jsx", startLine: 22, endLine: 33 },
        { kind: "source", fileName: "RenderingListsKeyDemo.jsx", startLine: 39, endLine: 46 },
      ],
    },
  },
};

const STATE_SNAPSHOT_QUEUE_MODEL = {
  learningUnitId: "state-snapshot-queue",
  version: 1,
  mechanismTitle: "先区分当前快照、更新请求和下一次 render",
  mechanismAriaLabel: "State Snapshot 与 Update Queue 机制区分",
  mechanismHeaders: {
    subject: "机制",
    example: "当前 Demo",
    role: "它负责什么",
    change: "同一次事件里会怎样",
  },
  contrastTitle: "三种队列，不要只看最后数字",
  contrastDimensions: [
    { id: "handlerStory", label: "当前 handler" },
    { id: "queueStory", label: "入队内容" },
    { id: "processingStory", label: "queue processing" },
    { id: "resultStory", label: "next render" },
  ],
  mechanismMap: [
    {
      id: "render-snapshot",
      label: "Render Snapshot",
      example: "count",
      role: "当前 render 已经得到的固定 State 值；事件 handler 读取的是这份快照。",
      change: "调用 setter 不会回头改写这份 count；当前 handler 后续读取仍看到同一 snapshot。",
    },
    {
      id: "update-request",
      label: "Update Request",
      example: "setCount(...)",
      role: "请求 React 为后续 render 计算新的 State，而不是直接修改当前变量。",
      change: "同一事件里的多个 setter 会形成一组待处理更新。",
    },
    {
      id: "replace-update",
      label: "Replace Update",
      example: "setCount(count + 1)",
      role: "先用当前 snapshot 计算一个具体值，再把“替换为这个值”的请求加入队列。",
      change: "count = 0 时连续三次都读取 0，因此三项都是 replace 1。",
    },
    {
      id: "updater-function",
      label: "Updater Function",
      example: "setCount(n => n + 1)",
      role: "把一个转换函数加入队列；React 处理队列时把上一项 pending state 传给它。",
      change: "三个 updater 会依次看到 0、1、2，并计算出 1、2、3。",
    },
    {
      id: "update-queue",
      label: "Update Queue",
      example: "replace → updater → replace",
      role: "按入队顺序处理本轮 State 更新，持续维护一个 pending state。",
      change: "replace 会直接设置 pending；updater 基于当前 pending 继续计算；后续 replace 还能再次覆盖 pending。",
    },
    {
      id: "next-render-state",
      label: "Next Render State",
      example: "scenario.result",
      role: "队列处理结束后的最终 pending value，会成为下一次 render 的 State。",
      change: "下一次 render 才拿到新的 snapshot；它与当前 handler 内仍在读取的旧 snapshot 是两回事。",
    },
  ],
  contrastCases: [
    {
      id: "replace-three",
      title: "Replace × 3",
      handlerStory: "当前 snapshot 是 0，三次表达式里的 count 都读取 0。",
      queueStory: "replace 1 → replace 1 → replace 1",
      processingStory: "pending 被设为 1，再设为 1，再设为 1。",
      resultStory: "下一次 render 得到 1。",
      conclusion: "调用了三次不等于基于前一次结果累加三次；三个 replace 值都来自同一份 snapshot。",
    },
    {
      id: "updater-three",
      title: "Updater × 3",
      handlerStory: "当前 snapshot 仍是 0；handler 本身不会看到 1、2、3。",
      queueStory: "+1 updater → +1 updater → +1 updater",
      processingStory: "pending 依次 0 → 1 → 2 → 3。",
      resultStory: "下一次 render 得到 3。",
      conclusion: "updater 的关键不是“更异步”，而是它基于 queue 中前一项的 pending state 继续计算。",
    },
    {
      id: "mixed-queue",
      title: "Replace + Updater + Replace 42",
      handlerStory: "所有直接读取 count 的表达式仍基于同一当前 snapshot。",
      queueStory: "replace count+5 → +1 updater → replace 42",
      processingStory: "先得到 count+5，再由 updater 得到 count+6，最后 replace 把 pending 设置为 42。",
      resultStory: "下一次 render 得到 42。",
      conclusion: "结果是 42 不代表 React 只保留最后一次调用；队列按顺序处理，只是最后一个 replace 改写了 pending。",
    },
  ],
  misconceptions: {
    "setter-mutates-snapshot": {
      id: "setter-mutates-snapshot",
      title: "认为 setter 会立即修改当前 render 里的 State 变量",
      diagnosis: "这里把“请求下一次 State”误解成了“改写当前 handler 已经读取到的 snapshot”。",
      counterEvidence: "Demo 会同时展示 handler snapshot 和 next render state：它们可以不同，说明 setter 没有回头改写当前 snapshot。",
      experiment: "Reset 后点击 Replace × 3。对比 Queue Debugger 的 handler snapshot 与 next render state：前者仍是 0，后者是 1。",
      evidenceRefs: [
        { kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 22, endLine: 27 },
        { kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 105, endLine: 127 },
      ],
    },
    "repeated-replace-accumulates": {
      id: "repeated-replace-accumulates",
      title: "认为三次 setCount(count + 1) 会自动基于前一次结果继续 +1",
      diagnosis: "三个表达式都在同一个 handler 中读取同一份 count snapshot，因此它们计算的是同一个 replacement value。",
      counterEvidence: "count = 0 时 Queue Debugger 明确显示三个 replace 都是 1，而下一次 render 只得到 1。",
      experiment: "Reset → Replace × 3；逐条读 Queue Debugger，确认三项都是 replace 1，而不是 1、2、3。",
      evidenceRefs: [{ kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 29, endLine: 45 }],
    },
    "updater-is-syntax-sugar": {
      id: "updater-is-syntax-sugar",
      title: "认为 updater function 只是 setCount(count + 1) 的另一种语法",
      diagnosis: "updater 会在 React 处理队列时接收当前 pending state；直接 replace 则把调用时已经算好的具体值入队。",
      counterEvidence: "同样连续调用三次，Replace × 3 从 0 得到 1，而 Updater × 3 得到 3。",
      experiment: "Reset 后分别运行 Replace × 3 和 Updater × 3，对比 Queue Debugger 的每一步输入值。",
      evidenceRefs: [
        { kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 29, endLine: 45 },
        { kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 47, endLine: 63 },
      ],
    },
    "queue-keeps-last-only": {
      id: "queue-keeps-last-only",
      title: "认为 batching 会让 React 只保留最后一次 setter",
      diagnosis: "batching 并不等于丢弃前面的更新；React 仍按顺序处理 queue 中的 replace 与 updater。",
      counterEvidence: "从 count = 0 运行 Replace + Updater 会得到 6；如果只保留最后一个 +1 updater，结果不会是 6。",
      experiment: "Reset → Replace + Updater。观察 debugger 先 replace 5，再执行 +1 updater 得到 6。",
      evidenceRefs: [{ kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 65, endLine: 79 }],
    },
    "same-result-same-semantics": {
      id: "same-result-same-semantics",
      title: "认为最终数字相同就代表更新语义相同",
      diagnosis: "单个 replace count+3 和三个 updater 在某个起点可以得到相同结果，但它们进入 queue 的内容与组合方式并不相同。",
      counterEvidence: "updater 会消费前一项 pending state，因此当它与其他更新混排时，行为取决于 queue 顺序；replace 是已经算好的具体值。",
      experiment: "先观察 Updater × 3 的 0→1→2→3，再观察 Replace + Updater，确认 updater 会接住前一项 pending，而不是重新读取 handler snapshot。",
      evidenceRefs: [
        { kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 47, endLine: 79 },
      ],
    },
    "last-result-means-last-only": {
      id: "last-result-means-last-only",
      title: "看到最终 42 就认为前面的 queue 项没有执行",
      diagnosis: "最后一个 replace 42 会把当时的 pending state 改成 42，但这不等于前面的 replace / updater 从未被处理。",
      counterEvidence: "Queue Debugger 会列出 count+5 和 +1 updater 的中间步骤，然后才显示 replace 42。",
      experiment: "运行 Replace + Updater + Replace 42，逐行查看 debugger；确认 42 是最后一步覆盖 pending 的结果。",
      evidenceRefs: [{ kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 81, endLine: 98 }],
    },
  },
};


const NOT_NEED_EFFECT_MODEL = {
  learningUnitId: "not-need-effect",
  version: 1,
  mechanismTitle: "先问“为什么它需要运行”，再决定放在哪里",
  mechanismAriaLabel: "You Might Not Need an Effect 因果边界",
  mechanismHeaders: {
    subject: "因果来源",
    example: "典型例子",
    role: "优先放哪里",
    change: "判断边界",
  },
  contrastTitle: "四类需求，关键不是“有没有副作用”，而是因果从哪里来",
  contrastDimensions: [
    { id: "causeStory", label: "为什么运行" },
    { id: "placementStory", label: "代码位置" },
    { id: "failureStory", label: "错放进 Effect 的代价" },
    { id: "boundaryStory", label: "边界" },
  ],
  mechanismMap: [
    {
      id: "render-derivation",
      label: "Render Derivation",
      example: "filteredProducts",
      role: "直接在 render 中根据当前 props/state 计算 UI 所需值。",
      change: "只要输入变了，React 本来就会重新 render；不需要再用 Effect 同步第二份 State。",
    },
    {
      id: "event-caused-logic",
      label: "Event-caused Logic",
      example: "handleBuy()",
      role: "放在触发这件事的 Event Handler 中。",
      change: "购买、提交、埋点等如果是因为这次明确点击发生，因果应停留在这次事件，而不是监听某个 State 变化再猜“发生了什么”。",
    },
    {
      id: "external-synchronization",
      label: "External Synchronization",
      example: "resize / subscription",
      role: "用 Effect 建立并清理与 React 外部系统的同步关系。",
      change: "组件存在期间需要订阅浏览器 API、连接、计时器或第三方 widget，并在依赖变化/卸载时重新同步或 cleanup。",
    },
    {
      id: "identity-reset",
      label: "Identity Reset",
      example: "key={userId}",
      role: "当产品语义是“这是另一个实体，旧局部 State 应丢弃”时，让 React 创建新的组件身份。",
      change: "它解决的是业务身份边界，不是所有 reset Effect 的通用替代品；若要保留每个实体草稿，应重新设计 State ownership。",
    },
    {
      id: "memoization",
      label: "Memoization",
      example: "expensive derive",
      role: "仍然先把纯计算留在 render；只有性能测量证明值得时，再考虑 memoization。",
      change: "“计算很贵”是性能问题，不会自动把纯计算变成 Effect。",
    },
  ],
  contrastCases: [
    {
      id: "derived-list",
      title: "过滤列表：render vs Effect + duplicate State",
      causeStory: "query / category 改变后，新的 UI 需要重新计算 filteredProducts。",
      placementStory: "直接在 render 中从现有 State 派生。",
      failureStory: "再存 filtered State 并用 Effect 同步，会制造第二份事实来源与额外 render / 同步链。",
      boundaryStory: "是否昂贵另行讨论；昂贵纯计算仍然不是 Effect 的理由。",
      conclusion: "能由当前 props/state 算出的 UI 数据，优先派生，不要先复制成第二份 State。",
    },
    {
      id: "purchase-event",
      title: "购买 POST / 埋点：Event Handler vs Effect watching State",
      causeStory: "代码之所以运行，是因为用户刚刚点击了“购买”。",
      placementStory: "在这次点击的 handler 中完成业务动作与记录。",
      failureStory: "改成 Effect 监听 purchasedCount，会丢失原始事件语义，并让“为什么运行”依赖间接 State 变化。",
      boundaryStory: "不是“网络请求都进 handler”；如果请求是为了组件显示期间与服务器/外部系统同步，因果来源不同。",
      conclusion: "明确用户动作触发的逻辑，应留在对应事件中，不要把 Effect 当事件代理。",
    },
    {
      id: "external-sync",
      title: "window.resize / subscription：真正的 Effect",
      causeStory: "组件显示期间，需要持续与浏览器或第三方外部系统保持同步。",
      placementStory: "Effect 中 setup，并返回 cleanup；决定同步目标的 reactive values 进入依赖。",
      failureStory: "放在 render 会重复制造副作用；只放在某个 click handler 又无法覆盖组件整个生命周期。",
      boundaryStory: "核心问题不是“依赖变没变”，而是“有没有 React 之外需要同步的系统”。",
      conclusion: "Effect 的主职责是外部同步，而不是通用的“值变化监听器”。",
    },
    {
      id: "identity-reset",
      title: "userId 切换：key reset vs Effect setState reset",
      causeStory: "产品把 User_A 与 User_B 视为不同业务身份，并希望旧留言草稿被丢弃。",
      placementStory: "用 key 表达身份边界，让新的 CommentForm 从初始 State 开始。",
      failureStory: "Effect 监听 userId 再 setComment 会先用旧 State render 一次，再额外同步；也把身份语义藏进命令式修补。",
      boundaryStory: "如果业务要求保留每个用户自己的草稿，就不应 reset，而应提升/按 userId 保存 State。",
      conclusion: "key reset 是 identity 决策，不是“看到 reset Effect 就一律换 key”。",
    },
  ],
  misconceptions: {
    "derived-needs-effect-state": {
      id: "derived-needs-effect-state",
      title: "认为派生数据必须存成第二份 State 再用 Effect 同步",
      diagnosis: "filteredProducts 已经完全由当前 query、category 与 products 决定；再同步一份 State 只会制造重复事实来源。",
      counterEvidence: "当前 Demo 不使用 Effect：修改搜索词或分类仍会在同一次 React render 中得到正确 filteredProducts。",
      experiment: "修改搜索词与分类，观察列表立即随当前输入变化；再对照源码 filteredProducts 直接在 render 中计算。",
      evidenceRefs: [{ kind: "source", fileName: "NotNeedEffectDemo.jsx", startLine: 41, endLine: 50 }],
    },
    "side-effect-means-effect": {
      id: "side-effect-means-effect",
      title: "认为“有副作用 / 有网络请求”就必须放进 Effect",
      diagnosis: "是否使用 Effect 不由“这段代码是不是副作用”决定，而要看它为什么运行。明确由一次用户点击触发的业务动作属于 Event Handler。",
      counterEvidence: "购买日志只在点击购买时产生；Demo 直接在 handleBuy 中记录，不需要监听 purchasedCount 才知道用户刚做了什么。",
      experiment: "连续点击不同商品的“购买”，观察每条日志都直接对应那次点击；再看 handleBuy 如何同时更新计数与日志。",
      evidenceRefs: [{ kind: "source", fileName: "NotNeedEffectDemo.jsx", startLine: 55, endLine: 64 }],
    },
    "state-change-needs-effect": {
      id: "state-change-needs-effect",
      title: "认为“某个 State 变化后要做事”就应该写 Effect 监听",
      diagnosis: "State 变化只是结果，不一定是原始因果。若逻辑真正由点击触发，监听 State 会把事件因果绕成间接变化监听。",
      counterEvidence: "purchasedCount 的变化来自 handleBuy；如果日志的真正原因是购买点击，handler 已经拥有更准确的因果信息与 productName。",
      experiment: "查看 handleBuy：同一事件里既知道 productName，也知道用户刚点击购买；比较这与 Effect 只能看到 purchasedCount 改变的差异。",
      evidenceRefs: [{ kind: "source", fileName: "NotNeedEffectDemo.jsx", startLine: 55, endLine: 64 }],
    },
    "effect-is-change-listener": {
      id: "effect-is-change-listener",
      title: "把 Effect 当成通用的“值变化监听器”",
      diagnosis: "Effect 的核心不是“有依赖变化就执行代码”，而是组件需要与 React 外部系统建立同步过程；依赖只描述这段同步何时需要重新建立。",
      counterEvidence: "query / category 变化不需要 Effect 就能更新派生列表；购买计数变化也不需要 Effect 才能处理点击。只有外部订阅、连接、DOM/浏览器 API 等同步才需要 Effect。",
      experiment: "把本节三类需求逐个问一遍：是在计算 UI、响应明确事件，还是在维持 React 外部系统同步？只有第三类属于 Effect。",
      evidenceRefs: [
        { kind: "source", fileName: "NotNeedEffectDemo.jsx", startLine: 45, endLine: 64 },
        { kind: "source", fileName: "NotNeedEffectDemo.jsx", startLine: 191, endLine: 197 },
      ],
    },
    "expensive-means-effect": {
      id: "expensive-means-effect",
      title: "认为计算昂贵就应该把它移进 Effect",
      diagnosis: "昂贵与否是性能优化问题；只要结果是纯粹由当前 props/state 推导，它仍属于 render 数据流。",
      counterEvidence: "Effect + State 并不会让派生逻辑变得更“正确”，反而会增加同步和额外 render。性能问题应先测量，再考虑 memoization。",
      experiment: "先判断 filteredProducts 是否依赖任何外部系统。答案仍是“没有”；因此即使未来数据量变大，也应先从纯派生 + 性能优化角度处理。",
      evidenceRefs: [{ kind: "source", fileName: "NotNeedEffectDemo.jsx", startLine: 45, endLine: 50 }],
    },
    "key-reset-is-universal": {
      id: "key-reset-is-universal",
      title: "认为 key reset 可以无条件替代任何 reset Effect",
      diagnosis: "key 表达的是组件身份。只有业务语义明确要求“切换实体后旧局部 State 应被丢弃”时，重建身份才正确。",
      counterEvidence: "Demo 的留言板把 User_A 与 User_B 当成不同身份，所以切换 key 会清空草稿；如果产品要求分别保留 A/B 草稿，这个 reset 就反而是错误需求。",
      experiment: "给 User_A 输入 AAA，切到 User_B 再切回来。观察 AAA 不会被保留；再问自己：这是不是当前产品真正想要的语义？",
      evidenceRefs: [
        { kind: "source", fileName: "NotNeedEffectDemo.jsx", startLine: 5, endLine: 24 },
        { kind: "source", fileName: "NotNeedEffectDemo.jsx", startLine: 236, endLine: 248 },
      ],
    },
  },
};

const PRESERVING_RESETTING_STATE_MODEL = {
  learningUnitId: "preserving-resetting-state",
  version: 1,
  mechanismTitle: "先判断 React 是否还在表示同一个组件身份",
  mechanismAriaLabel: "Preserving and Resetting State 身份机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它决定什么",
    change: "业务实体切换时",
  },
  contrastTitle: "State 应该保留还是 reset，取决于哪一层身份发生变化",
  contrastDimensions: [
    { id: "inputStory", label: "输入 / 结构" },
    { id: "identityStory", label: "组件身份" },
    { id: "stateStory", label: "局部 State" },
    { id: "productStory", label: "产品语义" },
  ],
  mechanismMap: [
    {
      id: "business-entity",
      label: "业务实体",
      example: "Taylor / Alice",
      role: "产品真正想区分的聊天对象、客户、编辑对象。",
      change: "实体可以变化，但是否要创建新 UI 身份由产品语义决定。",
    },
    {
      id: "tree-slot",
      label: "Parent / tree slot",
      example: "<Chat ... /> 的位置",
      role: "React 在同一父级下比较前后 render 的对应位置。",
      change: "同一位置继续出现兼容元素时，身份有机会延续。",
    },
    {
      id: "component-type",
      label: "Component type",
      example: "Chat",
      role: "类型不同意味着不是同一个组件身份。",
      change: "Taylor → Alice 时组件类型仍然是 Chat。",
    },
    {
      id: "key",
      label: "key",
      example: "无 key / contact.id",
      role: "在同一父级中参与显式身份匹配。",
      change: "无 key 时联系人变化不改身份；contact.id 变化时显式要求新身份。",
    },
    {
      id: "component-identity",
      label: "Component Identity",
      example: "当前 Chat 实例",
      role: "React 判断前后 render 是否仍是同一个组件实例的结果。",
      change: "身份延续就保留其 State；身份不匹配就丢弃旧实例并创建新实例。",
    },
    {
      id: "local-state",
      label: "Local State",
      example: "draft",
      role: "属于 React 组件身份，不自动属于 contact 对象或某个 prop 值。",
      change: "组件身份保留就继续存在；新身份从 useState 初始值开始。",
    },
  ],
  contrastCases: [
    {
      id: "prop-change-preserves",
      title: "同位置 + 同类型 + 无 key 变化",
      inputStory: "contact 从 Taylor 变成 Alice，但父级仍在同一位置渲染 <Chat contact={...} />。",
      identityStory: "React 仍匹配到同一个 Chat 组件身份；Props 更新不等于身份 reset。",
      stateStory: "Taylor 时输入的 draft 继续保留，并出现在 Alice 的 Chat 中。",
      productStory: "如果聊天对象切换后旧草稿不应继承，这种“技术上保留”就是产品风险。",
      conclusion: "Props 可以变化，同时局部 State 仍属于被保留的组件身份。",
    },
    {
      id: "business-key-resets",
      title: "同位置 + 同类型 + key={contact.id}",
      inputStory: "contact 与 key 从 Taylor/taylor 一起变成 Alice/alice。",
      identityStory: "显式 key 不再匹配旧 Chat，React 丢弃旧身份并创建新的 Chat 身份。",
      stateStory: "新 Chat 的 draft 从 useState(\"\") 初始值开始。",
      productStory: "当“不同联系人 = 不同聊天实例”且旧草稿应丢弃时，这个 reset 与业务边界一致。",
      conclusion: "key 不是刷新按钮；它是在告诉 React 这里应该是另一个组件身份。",
    },
    {
      id: "narrow-reset-boundary",
      title: "只 reset 真正属于新实体的子树",
      inputStory: "WorkspaceShell 保存面板/滚动 State；InvoiceEditor 保存当前 customer 的未提交草稿。",
      identityStory: "Shell 应继续是同一个工作区身份；Editor 才应随 customer.id 获得新身份。",
      stateStory: "Shell State 保留，InvoiceEditor 草稿 reset。",
      productStory: "把 key 放到需要 reset 的最窄业务边界，避免无关 UI State 一起丢失。",
      conclusion: "identity boundary 的位置本身就是产品设计决策。",
    },
    {
      id: "unstable-key-over-resets",
      title: "随机 / 不稳定 key",
      inputStory: "key 与业务实体无关，在普通 render 中也不断变化。",
      identityStory: "React 无法延续组件身份，每次都被迫创建新身份。",
      stateStory: "局部 State 在无关 render 中也不断重新初始化。",
      productStory: "虽然看起来“总能清空”，却破坏了该保留的 UI 状态和生命周期。",
      conclusion: "能造成 reset 不代表 identity 设计正确；key 必须表达稳定业务身份。",
    },
  ],
  misconceptions: {
    "props-reset-state": {
      id: "props-reset-state",
      title: "认为 Props 变化会自动重置子组件的局部 State",
      diagnosis: "Props 是当前 render 的输入；只要 React 仍匹配到同一个组件身份，Props 可以更新而这个身份上的 local State 继续保留。",
      counterEvidence: "Demo 上半区从 Taylor 切到 Alice 后收件人文字会更新，但 textarea 中原 draft 仍然存在。",
      experiment: "在上半区给 Taylor 输入 AAA，再点击 Alice：同时观察“当前收件人”已经变化，而 AAA 仍保留。",
      evidenceRefs: [{ kind: "source", fileName: "PreservingResettingStateDemo.jsx", startLine: 72, endLine: 86 }],
    },
    "state-follows-business-object": {
      id: "state-follows-business-object",
      title: "认为 local State 会自动跟随当前 contact / customer 业务对象",
      diagnosis: "useState 创建的 draft 属于 React component identity；React 不会因为 contact 对象换了，就自动替每个联系人保存或恢复一份独立 draft。",
      counterEvidence: "无 key 的 Chat 切到 Alice 时，Taylor 的 draft 会继续出现在同一个 Chat 身份里，而不是自动切换到 Alice 专属 State。",
      experiment: "Taylor 输入一段独特草稿后切 Alice，再切 Bob，观察同一份 draft 如何跨不同 contact Props 继续存在。",
      evidenceRefs: [
        { kind: "source", fileName: "PreservingResettingStateDemo.jsx", startLine: 9, endLine: 28 },
        { kind: "source", fileName: "PreservingResettingStateDemo.jsx", startLine: 72, endLine: 82 },
      ],
    },
    "key-only-for-lists": {
      id: "key-only-for-lists",
      title: "认为 key 只用于列表或消除 warning",
      diagnosis: "key 的语义是同一父级下的身份线索。列表是最常见场景，但非列表位置也可以用 key 明确表达“这是另一个组件身份”。",
      counterEvidence: "Demo 下半区只有一个 Chat，不是 map 列表；key={contact.id} 仍直接控制联系人切换时是否保留 Chat identity。",
      experiment: "对比上下两个单独 Chat：唯一关键差异是下半区给 Chat 加了 contact.id key，切联系人时只有下半区 draft reset。",
      evidenceRefs: [{ kind: "source", fileName: "PreservingResettingStateDemo.jsx", startLine: 89, endLine: 100 }],
    },
    "key-is-dom-refresh": {
      id: "key-is-dom-refresh",
      title: "把 key 变化理解成“强制刷新 DOM”",
      diagnosis: "关键变化发生在 React component identity：旧组件身份被丢弃，新组件重新初始化 State。DOM 变化只是随后 commit 的界面结果。",
      counterEvidence: "Demo 的直接语义是旧 Chat identity unmount、新 Chat identity mount，并因此重新执行 useState 初始值；不是对原 State 做清空命令。",
      experiment: "先看 Chat 的 useState(\"\")，再切换下半区联系人：解释为什么新的 draft 是空值，而不是把现有 draft 字符串手动改成空。",
      evidenceRefs: [
        { kind: "source", fileName: "PreservingResettingStateDemo.jsx", startLine: 9, endLine: 28 },
        { kind: "source", fileName: "PreservingResettingStateDemo.jsx", startLine: 91, endLine: 99 },
      ],
    },
    "random-key-is-reset-strategy": {
      id: "random-key-is-reset-strategy",
      title: "认为随机 key 是通用、可靠的 reset 方案",
      diagnosis: "随机 key 不表达业务身份；它会让组件在无关 render 中也失去身份，造成不必要的卸载、挂载和 State 丢失。",
      counterEvidence: "当前 Demo 使用稳定 contact.id：同一联系人普通 render 时 key 不变，只有业务实体变化才 reset。",
      experiment: "比较“key={contact.id}”与“每次 render 都变化的 key”：问哪一种能表达“只在联系人真的变化时 reset”。",
      evidenceRefs: [
        { kind: "source", fileName: "PreservingResettingStateDemo.jsx", startLine: 96, endLine: 99 },
        { kind: "source", fileName: "PreservingResettingStateDemo.jsx", startLine: 125, endLine: 136 },
      ],
    },
    "reset-boundary-too-high": {
      id: "reset-boundary-too-high",
      title: "认为某个子组件要 reset，就应该给更外层整个页面/工作区加 key",
      diagnosis: "key 会重置它所在的组件身份及其子树。把 identity boundary 放得过高，会把本应保留的面板、滚动、展开等 UI State 一起丢弃。",
      counterEvidence: "当前 Guided 迁移题要求 WorkspaceShell 保留 UI State、只有 InvoiceEditor 草稿随 customer 切换 reset；正确边界因此是 Editor 本身。",
      experiment: "把需求拆成两列：哪些 State 属于“工作区”应保留，哪些 State 属于“当前 customer 编辑器”应 reset，再决定 key 放在哪一层。",
      evidenceRefs: [{ kind: "source", fileName: "PreservingResettingStateDemo.jsx", startLine: 125, endLine: 136 }],
    },
  },
};

function deepFreeze(value, visited = new WeakSet()) {
  if (!value || typeof value !== "object" || visited.has(value)) return value;
  visited.add(value);
  Object.values(value).forEach((child) => deepFreeze(child, visited));
  return Object.freeze(value);
}

export const CONCEPT_MODELS = deepFreeze({
  [LISTS_KEY_MODEL.learningUnitId]: LISTS_KEY_MODEL,
  [STATE_SNAPSHOT_QUEUE_MODEL.learningUnitId]: STATE_SNAPSHOT_QUEUE_MODEL,
  [NOT_NEED_EFFECT_MODEL.learningUnitId]: NOT_NEED_EFFECT_MODEL,
  [PRESERVING_RESETTING_STATE_MODEL.learningUnitId]: PRESERVING_RESETTING_STATE_MODEL,
});

export function getConceptModelForLearningUnit(learningUnitId) {
  return CONCEPT_MODELS[learningUnitId] ?? null;
}

export function getMisconceptionForLearningUnit(learningUnitId, misconceptionId) {
  if (!learningUnitId || !misconceptionId) return null;
  return CONCEPT_MODELS[learningUnitId]?.misconceptions?.[misconceptionId] ?? null;
}
