import {
  Callout,
  MentalModel,
  Concept,
  Experiment,
  Observation,
  Compare,
  Timeline,
  Flow,
  Boundary,
  AntiPattern,
  CodeBlock,
  CodeDiff,
  DemoReference,
  Summary,
  FurtherReading,
} from "./TeachingComponents";

export {
  Callout,
  MentalModel,
  Concept,
  Experiment,
  Observation,
  Compare,
  Timeline,
  Flow,
  Boundary,
  AntiPattern,
  CodeBlock,
  CodeDiff,
  DemoReference,
  Summary,
  FurtherReading,
};

export const MDX_TEACHING_COMPONENT_NAMES = Object.freeze([
  "Callout",
  "MentalModel",
  "Concept",
  "Experiment",
  "Observation",
  "Compare",
  "Timeline",
  "Flow",
  "Boundary",
  "AntiPattern",
  "CodeBlock",
  "CodeDiff",
  "DemoReference",
  "Summary",
  "FurtherReading",
]);

export const MDX_TEACHING_COMPONENT_CONTRACT_VERSION = 1;

export const MDX_TEACHING_COMPONENTS = Object.freeze({
  Callout,
  MentalModel,
  Concept,
  Experiment,
  Observation,
  Compare,
  Timeline,
  Flow,
  Boundary,
  AntiPattern,
  CodeBlock,
  CodeDiff,
  DemoReference,
  Summary,
  FurtherReading,
});
