export const CHILDREN_MODEL = {
  learningUnitId: "children",
  version: 1,
  mechanismTitle: "调用者决定内容，容器决定外壳",
  mechanismAriaLabel: "Children composition 机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它负责什么",
    change: "内容变化时",
  },
  contrastTitle: "结构组合与配置 Props 不要互相替代",
  codeEvidence: [
    {
      id: "container-renders-children",
      title: "容器只声明插槽，不读取业务内容字段",
      explanation: "CardContainer 接收 children，并在自己拥有的卡片外壳里直接渲染它；容器无需知道里面是说明文字、按钮还是表单。",
      sourceRef: { kind: "source", fileName: "CardContainer.jsx", startLine: 41, endLine: 45 },
    },
    {
      id: "caller-provides-structure",
      title: "具体 JSX 由调用位置组装",
      explanation: "同一个 CardContainer 在调用处嵌入完全不同的 React 节点，结构变化发生在调用者，而不是容器内部不断增加 type/boolean 分支。",
      sourceRef: { kind: "source", fileName: "ChildrenSlotDemo.jsx", startLine: 52, endLine: 73 },
    },
  ],
  mechanismMap: [
    {
      id: "caller",
      label: "调用者",
      example: "ChildrenSlotDemo",
      role: "知道业务内容是什么，并组装具体 React 节点。",
      change: "可以替换传入结构，而不修改容器实现。",
    },
    {
      id: "children",
      label: "children",
      example: "<form>…</form>",
      role: "把调用位置嵌套的 React 节点传给容器。",
      change: "它可以是文本、元素、组件树或空内容。",
    },
    {
      id: "container",
      label: "容器",
      example: "CardContainer / ModalLayout",
      role: "拥有布局、视觉外壳以及自身明确的交互职责。",
      change: "保持稳定 API，不需要知道 children 的业务字段。",
    },
    {
      id: "composed-tree",
      label: "组合后的树",
      example: "Shell + caller content",
      role: "React 最终得到一棵由双方职责拼成的元素树。",
      change: "结构复用来自组合，而不是继承模板。",
    },
  ],
  contrastCases: [
    {
      id: "structural-variation",
      title: "内部结构差异很大",
      keyStory: "调用者知道要放什么。",
      identityStory: "容器 API 保持稳定。",
      stateStory: "内容自身的状态仍由内容组件拥有。",
      uiStory: "优先 children / slot composition。",
      conclusion: "结构变化属于调用者时，让调用者直接提供 JSX。",
    },
    {
      id: "semantic-config",
      title: "少量稳定配置",
      keyStory: "例如 title、size、tone。",
      identityStory: "语义参数清晰且有限。",
      stateStory: "不需要把整个结构外包给调用者。",
      uiStory: "普通显式 props 更直接。",
      conclusion: "组合不是为了消灭所有配置 Props。",
    },
  ],
  misconceptions: {
    "children-is-string": {
      id: "children-is-string",
      title: "把 children 当成 HTML 字符串插槽",
      diagnosis: "children 是 React node 数据，可以包含元素、组件、文本、数组等，不要求容器解析 HTML 字符串。",
      counterEvidence: "Demo 直接把完整 form JSX 作为 CardContainer 的 children 传入并保持交互。",
      experiment: "查看反馈卡片调用处：表单逻辑位于调用者，CardContainer 只渲染 {children}。",
      evidenceRefs: [
        { kind: "source", fileName: "ChildrenSlotDemo.jsx", startLine: 69, endLine: 96 },
        { kind: "source", fileName: "CardContainer.jsx", startLine: 41, endLine: 45 },
      ],
    },
    "container-owns-child-business": {
      id: "container-owns-child-business",
      title: "认为容器必须知道 children 的业务语义",
      diagnosis: "组合的价值恰恰是让 shell 与业务内容解耦；容器只实现它真正拥有的布局/交互。",
      counterEvidence: "CardContainer 同时承载通知和表单，却没有任何 feedback/message 类型分支。",
      experiment: "比较两个 CardContainer 调用点，再检查 CardContainer 本体是否读取表单字段。",
      evidenceRefs: [{ kind: "source", fileName: "CardContainer.jsx", startLine: 6, endLine: 45 }],
    },
    "composition-replaces-props": {
      id: "composition-replaces-props",
      title: "认为用了 children 就不该再有普通 Props",
      diagnosis: "结构插槽与稳定语义参数职责不同；title/subtitle 等显式配置仍然可以比结构插槽更清楚。",
      counterEvidence: "CardContainer 同时使用 title/subtitle/extra 与 children，各自表达不同类型的 API。",
      experiment: "指出哪些参数决定稳定外壳语义，哪些内容需要由调用者自由组合。",
      evidenceRefs: [{ kind: "source", fileName: "CardContainer.jsx", startLine: 6, endLine: 18 }],
    },
  },
};
