export const COMPONENT_JSX_PURE_RENDER_MODEL = {
  learningUnitId: "component-jsx-pure-render",
  version: 1,
  mechanismTitle: "把 render 当成可重复执行的 UI 计算",
  mechanismAriaLabel: "Component JSX pure render 机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它负责什么",
    change: "重复执行时",
  },
  contrastTitle: "纯计算、组件树与 DOM commit 不要混在一起",
  codeEvidence: [
    {
      id: "pure-vs-impure-calculation",
      title: "相同输入为什么应该得到相同结果",
      explanation: "纯函数只根据 name/count 计算字符串；非纯函数修改组件外部的 impureSequence，所以相同输入重复执行也会漂移。",
      sourceRef: { kind: "source", fileName: "ComponentJsxPureRenderDemo.jsx", startLine: 5, endLine: 11 },
    },
    {
      id: "repeat-calculation-experiment",
      title: "Demo 如何把纯度差异变成可观察证据",
      explanation: "按钮不是在测量真实 React render 次数，而是安全地用相同输入重复调用两类计算，直接对比结果是否稳定。",
      sourceRef: { kind: "source", fileName: "ComponentJsxPureRenderDemo.jsx", startLine: 48, endLine: 59 },
    },
  ],
  mechanismMap: [
    {
      id: "render-input",
      label: "Render 输入",
      example: "Props / State / Context",
      role: "一次组件函数执行可读取的当前输入。",
      change: "输入相同，纯 render 的 UI 描述应保持一致。",
    },
    {
      id: "component-function",
      label: "组件函数",
      example: "ProductSummary",
      role: "根据当前输入计算 React 元素描述。",
      change: "React 可以再次调用它；重复调用本身不等于 DOM 一定变化。",
    },
    {
      id: "jsx-description",
      label: "JSX",
      example: "<strong>{name}</strong>",
      role: "JavaScript 中的 UI 描述语法，不是直接操作 DOM。",
      change: "新的 JSX 描述交给 React 比较，而不是组件自己写 DOM。",
    },
    {
      id: "commit",
      label: "Commit",
      example: "必要的 DOM 变化",
      role: "React 把需要的宿主环境变更提交出去。",
      change: "组件函数执行次数与 commit 次数不是一一对应。",
    },
  ],
  contrastCases: [
    {
      id: "pure-calculation",
      title: "相同输入的纯计算",
      keyStory: "不修改 render 前已存在的外部数据。",
      identityStory: "可安全重复执行。",
      stateStory: "只读取本次输入并计算结果。",
      uiStory: "相同输入得到相同 UI 描述。",
      conclusion: "这是 React 可以重试 render 的基础。",
    },
    {
      id: "render-side-effect",
      title: "render 中修改外部值",
      keyStory: "计算过程顺手改变了外部世界。",
      identityStory: "重复调用会累积额外影响。",
      stateStory: "结果不再只由当前输入决定。",
      uiStory: "相同输入也可能出现不同输出。",
      conclusion: "这类副作用应离开 render。",
    },
  ],
  misconceptions: {
    "render-directly-mutates-dom": {
      id: "render-directly-mutates-dom",
      title: "认为组件函数执行就等于 DOM 已更新",
      diagnosis: "组件函数首先计算 React 元素描述；是否需要 DOM 变化由后续 reconciliation/commit 决定。",
      counterEvidence: "同一个组件函数可以被重复调用，但相同结果并不要求每次都产生新的 DOM 变更。",
      experiment: "运行纯/非纯重复计算实验，再对照后续 render-commit 课程；不要把本 Demo 当作真实 commit 计数器。",
      evidenceRefs: [{ kind: "source", fileName: "ComponentJsxPureRenderDemo.jsx", startLine: 48, endLine: 59 }],
    },
    "strict-mode-means-bug": {
      id: "strict-mode-means-bug",
      title: "把开发期重复调用当成 React 的错误",
      diagnosis: "React 可以为了发现非纯逻辑而重复调用组件计算；纯 render 应该能够承受重复执行。",
      counterEvidence: "纯函数相同输入重复两次仍得到同样结果，非纯函数才暴露漂移。",
      experiment: "点击“模拟相同输入重复 Render 两次”，比较 pure 与 impure 两组结果。",
      evidenceRefs: [{ kind: "source", fileName: "ComponentJsxPureRenderDemo.jsx", startLine: 5, endLine: 11 }],
    },
    "all-mutation-forbidden": {
      id: "all-mutation-forbidden",
      title: "认为 render 中任何 mutation 都绝对禁止",
      diagnosis: "真正的边界是不要修改 render 开始前已经存在、可被其他代码观察的外部数据。",
      counterEvidence: "本次 render 内新建且尚未逃逸的局部对象可以被构造或修改；问题是外部可观察副作用。",
      experiment: "区分“新建局部数组后 push”与“修改模块级数组”这两种代码的所有权。",
      evidenceRefs: [{ kind: "source", fileName: "ComponentJsxPureRenderDemo.jsx", startLine: 3, endLine: 11 }],
    },
  },
};
