export const CONDITIONAL_RENDERING_MODEL = {
  learningUnitId: "conditional-rendering",
  version: 1,
  mechanismTitle: "先把业务状态建模清楚，再映射成 JSX 分支",
  mechanismAriaLabel: "Conditional rendering 状态到 UI 映射",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它负责什么",
    change: "状态变化时",
  },
  contrastTitle: "业务状态建模比 if / ternary / && 语法选择更重要",
  codeEvidence: [
    {
      id: "early-return-status",
      title: "阻断态用独立 early return 表达",
      explanation: "ResultPanel 先处理 loading 分支并直接返回对应 JSX，使互斥业务态保持清楚，而不是把所有情况压进嵌套表达式。",
      sourceRef: { kind: "source", fileName: "ConditionalRenderingDemo.jsx", startLine: 5, endLine: 13 },
    },
    {
      id: "optional-debug-and",
      title: "&& 只表达一个真正的布尔开关",
      explanation: "showDebug 本身是 boolean，因此 && 很适合表达“有或没有这一小段调试 UI”；这与用数字等非 boolean 值做左操作数不同。",
      sourceRef: { kind: "source", fileName: "ConditionalRenderingDemo.jsx", startLine: 109, endLine: 120 },
    },
  ],
  mechanismMap: [
    {
      id: "business-state",
      label: "业务状态",
      example: "loading / empty / error / success",
      role: "描述当前系统处于哪一种有意义的情境。",
      change: "状态转换决定下一个 UI 分支。",
    },
    {
      id: "branch-priority",
      label: "分支优先级",
      example: "loading / error early return",
      role: "让阻断态先结束当前 render 路径。",
      change: "避免互斥状态同时显示。",
    },
    {
      id: "derived-condition",
      label: "派生条件",
      example: "isTerminal",
      role: "从当前状态直接计算展示判断。",
      change: "不必再复制一份 State。",
    },
    {
      id: "jsx-branch",
      label: "JSX 分支",
      example: "ResultPanel",
      role: "把当前状态映射成用户真正看到的界面。",
      change: "语法可以不同，但业务语义必须一致。",
    },
  ],
  contrastCases: [
    {
      id: "explicit-state",
      title: "互斥状态机",
      keyStory: "一个 status 表达当前情境。",
      identityStory: "非法组合更少。",
      stateStory: "状态事实集中。",
      uiStory: "每个 status 映射一个清晰分支。",
      conclusion: "复杂互斥 UI 优先让状态模型先变清楚。",
    },
    {
      id: "loose-booleans",
      title: "多个松散 boolean",
      keyStory: "isLoading / hasError / isEmpty 可同时为 true。",
      identityStory: "组合数量迅速增加。",
      stateStory: "容易出现矛盾事实。",
      uiStory: "分支优先级变得隐含。",
      conclusion: "语法再漂亮也无法修复错误的状态建模。",
    },
  ],
  misconceptions: {
    "conditional-is-react-directive": {
      id: "conditional-is-react-directive",
      title: "寻找 React 专属条件指令",
      diagnosis: "React JSX 直接使用 JavaScript 控制流；真正需要设计的是状态和分支，不是另一套模板语言。",
      counterEvidence: "ResultPanel 用普通 if/return，StatusBadge 用 ternary，调试块用 &&。",
      experiment: "分别定位三种 JavaScript 写法并确认它们最终都只是决定返回哪些 React node。",
      evidenceRefs: [{ kind: "source", fileName: "ConditionalRenderingDemo.jsx", startLine: 5, endLine: 48 }],
    },
    "loose-booleans-state": {
      id: "loose-booleans-state",
      title: "用多个 boolean 保存同一个互斥状态",
      diagnosis: "如果这些 boolean 可以组成互相矛盾的值，State 已经不能可靠表达真实业务状态。",
      counterEvidence: "Demo 用单一 status 在四态之间切换，任一时刻只代表一个状态。",
      experiment: "尝试用 isLoading/hasError/isEmpty 三个 boolean 列出可能组合，再找出非法组合。",
      evidenceRefs: [{ kind: "source", fileName: "ConditionalRenderingDemo.jsx", startLine: 3, endLine: 5 }],
    },
    "and-always-boolean": {
      id: "and-always-boolean",
      title: "认为 condition && JSX 左侧不会渲染任何值",
      diagnosis: "JavaScript && 返回操作数本身；如果左侧是 0，React 可能把 0 渲染出来。",
      counterEvidence: "当前 Demo 使用真正的 boolean showDebug，因此没有这个问题；把左值换成 count 才会暴露差异。",
      experiment: "比较 {showDebug && <Panel />} 与 {count && <Panel />} 在 false 和 0 时的 JavaScript 结果。",
      evidenceRefs: [{ kind: "source", fileName: "ConditionalRenderingDemo.jsx", startLine: 109, endLine: 120 }],
    },
  },
};
