export const CONTEXT_PROPAGATION_MODEL = {
  learningUnitId: "context-propagation",
  version: 1,
  mechanismTitle: "useContext 既读取最近 Provider，也建立对该 value 的订阅",
  mechanismAriaLabel: "Context 更新传播机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它负责什么",
    change: "Provider value 变化时",
  },
  contrastTitle: "memo 比较 props，但不能屏蔽组件自己消费的 Context",
  contrastDimensions: [
    { id: "readStory", label: "读取" },
    { id: "subscriptionStory", label: "订阅" },
    { id: "memoStory", label: "memo" },
    { id: "updateStory", label: "更新" },
  ],
  codeEvidence: [
    {
      id: "memo-consumer-context-read",
      title: "memoized consumer 仍然调用 useContext",
      explanation: "MemoConsumer 即使被 memo 包裹，仍订阅 ThemeContext；Context value 变化需要让它重新计算以读取新 theme。",
      sourceRef: { kind: "source", fileName: "ContextPropagationDemo.jsx", startLine: 34, endLine: 45 },
    },
    {
      id: "provider-value-and-consumers",
      title: "同一 Provider value 服务普通 consumer、memo consumer 与 non-consumer",
      explanation: "theme 改变时读取 ThemeContext 的两个组件需要新值；没有读取 Context 的 memo Non-consumer 不会因为 Context 订阅本身被通知。",
      sourceRef: { kind: "source", fileName: "ContextPropagationDemo.jsx", startLine: 112, endLine: 118 },
    },
  ],
  mechanismMap: [
    {
      id: "context",
      label: "Context",
      example: "ThemeContext",
      role: "定义一条跨层依赖通道。",
      change: "本身不等于全局 store。",
    },
    {
      id: "provider",
      label: "Provider value",
      example: "value={theme}",
      role: "提供最近的当前值。",
      change: "Object.is 比较为不同后通知消费者。",
    },
    {
      id: "consumer",
      label: "Consumer",
      example: "useContext(ThemeContext)",
      role: "读取最近 Provider 并订阅这条 Context。",
      change: "收到新 value 后重新 render。",
    },
    {
      id: "memo",
      label: "memo",
      example: "memo(MemoConsumer)",
      role: "可跳过仅由相同 props 导致的重复工作。",
      change: "不会取消组件自己的 Context 订阅。",
    },
  ],
  contrastCases: [
    {
      id: "memo-non-consumer",
      title: "memo + 不读取 Context",
      readStory: "不调用 useContext。",
      subscriptionStory: "没有 ThemeContext 订阅。",
      memoStory: "props 不变时可跳过父级带来的工作。",
      updateStory: "theme Context 更新本身不会通知它。",
      conclusion: "是否是 Context consumer 取决于读取关系，不取决于组件位置。",
    },
    {
      id: "memo-consumer",
      title: "memo + 读取 Context",
      readStory: "调用 useContext(ThemeContext)。",
      subscriptionStory: "订阅整个 ThemeContext value。",
      memoStory: "memo 仍只解决 props 比较边界。",
      updateStory: "theme 变化时必须得到新 Context value。",
      conclusion: "memo 不能把 stale Context 值冻结在消费者中。",
    },
  ],
  misconceptions: {
    "memo-blocks-context": {
      id: "memo-blocks-context",
      title: "认为 memo 会阻止 Context value 更新消费者",
      diagnosis: "memo 主要比较 props；组件自己的 Context 订阅仍会触发它读取新值。",
      counterEvidence: "Demo 的 MemoConsumer 同时使用 memo 与 useContext，theme 改变时仍会重新执行。",
      experiment: "只切换 Theme，比较 MemoConsumer 与 MemoNonConsumer。",
      evidenceRefs: [{ kind: "source", fileName: "ContextPropagationDemo.jsx", startLine: 34, endLine: 45 }],
    },
    "context-is-global-variable": {
      id: "context-is-global-variable",
      title: "认为 Context 是读取一次、不会触发更新的全局变量",
      diagnosis: "useContext 是响应式读取，会订阅最近 Provider value。",
      counterEvidence: "Provider 的 theme 更新后 Consumer 读取到新值。",
      experiment: "点击“切换 Theme”，观察 Consumer 显示和执行探针。",
      evidenceRefs: [{ kind: "source", fileName: "ContextPropagationDemo.jsx", startLine: 112, endLine: 118 }],
    },
    "context-has-field-selectors": {
      id: "context-has-field-selectors",
      title: "认为对象 Context 会自动只通知读取了某个字段的消费者",
      diagnosis: "原生 Context 订阅的是整个 value identity，没有对象字段级 selector 语义。",
      counterEvidence: "需要缩小订阅面时应调整 Provider/value 粒度或拆分 Context。",
      experiment: "设想 value={ {theme, cursor} } 且 cursor 高频变化，问只读 theme 的 consumer 是否拥有字段 selector。",
      evidenceRefs: [{ kind: "source", fileName: "ContextPropagationDemo.jsx", startLine: 112, endLine: 118 }],
    },
  },
};
