export const CONTROLLED_UNCONTROLLED_MODEL = {
  learningUnitId: "controlled-uncontrolled",
  version: 1,
  mechanismTitle: "先确认这份 State 的最终决定权属于谁",
  mechanismAriaLabel: "Controlled 与 Uncontrolled ownership 机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它代表什么",
    change: "交互后",
  },
  contrastTitle: "value 是权威事实，onChange 是意图，defaultValue 只是初始值",
  contrastDimensions: [
    { id: "ownerStory", label: "Owner" },
    { id: "inputStory", label: "输入" },
    { id: "interactionStory", label: "交互" },
    { id: "updateStory", label: "最终值" },
  ],
  codeEvidence: [
    {
      id: "tabs-authority-switch",
      title: "同一个 Tabs 明确选择外部 value 或内部 State 作为权威值",
      explanation: "value 存在时 activeValue 只读取外部输入；否则读取由 defaultValue 初始化的 internalValue。onChange 始终只是向外通知意图。",
      sourceRef: { kind: "source", fileName: "ControlledUncontrolledDemo.jsx", startLine: 9, endLine: 19 },
    },
    {
      id: "default-value-remount",
      title: "defaultValue 改变不持续覆盖，新的 key 才创建新实例",
      explanation: "父级可以改变 uncontrolledDefault，但已挂载 Tabs 的 internalValue 不会因此被重写；改变 key 重新挂载时才重新读取初始值。",
      sourceRef: { kind: "source", fileName: "ControlledUncontrolledDemo.jsx", startLine: 156, endLine: 168 },
    },
  ],
  mechanismMap: [
    {
      id: "controlled-value",
      label: "Controlled value",
      example: "value={controlledValue}",
      role: "父级提供的当前权威值。",
      change: "子组件请求后，只有父级传回新 value 才改变 UI。",
    },
    {
      id: "intent",
      label: "Intent",
      example: "onChange(next)",
      role: "子组件报告用户想要的下一值。",
      change: "父级可以接受、拒绝或转换。",
    },
    {
      id: "uncontrolled-state",
      label: "Internal State",
      example: "internalValue",
      role: "非受控模式的当前权威值。",
      change: "由组件自己的交互更新。",
    },
    {
      id: "initial-value",
      label: "Initial value",
      example: "defaultValue",
      role: "只用于初始化新的非受控实例。",
      change: "挂载后改变它不会持续同步 internalValue。",
    },
  ],
  contrastCases: [
    {
      id: "controlled",
      title: "Controlled",
      ownerStory: "父级拥有当前值。",
      inputStory: "子组件读取 value。",
      interactionStory: "子组件调用 onChange(next) 表达意图。",
      updateStory: "父级决定是否传回新的 value。",
      conclusion: "请求发生不等于 UI 已切换；authority 仍在 owner。",
    },
    {
      id: "uncontrolled",
      title: "Uncontrolled",
      ownerStory: "组件内部拥有当前值。",
      inputStory: "defaultValue 只初始化 internal State。",
      interactionStory: "组件自己更新 internalValue，同时可通知父级。",
      updateStory: "之后父级改 defaultValue 不覆盖当前值。",
      conclusion: "需要重新初始化时，应该明确创建新实例或设计 reset API。",
    },
  ],
  misconceptions: {
    "onchange-is-authority": {
      id: "onchange-is-authority",
      title: "认为 onChange 被调用就代表受控值已经改变",
      diagnosis: "onChange 只是意图；受控 UI 下一次显示什么仍由父级 value 决定。",
      counterEvidence: "Demo 父级可以拒绝 settings：onChange 日志出现，但 value 不变，Tabs 也不切换。",
      experiment: "保持“拒绝 settings”开启点击设置，再关闭限制重试。",
      evidenceRefs: [{ kind: "source", fileName: "ControlledUncontrolledDemo.jsx", startLine: 63, endLine: 73 }],
    },
    "default-value-controls-after-mount": {
      id: "default-value-controls-after-mount",
      title: "认为 defaultValue 会像 value 一样持续控制当前值",
      diagnosis: "defaultValue 只参与初始化；已挂载实例的 current value 由内部 State 决定。",
      counterEvidence: "Demo 改 uncontrolledDefault 后当前 tab 不变，只有新 key remount 才使用新的初始值。",
      experiment: "先切换非受控 Tab，再改 defaultValue，最后使用新 key 重新挂载。",
      evidenceRefs: [{ kind: "source", fileName: "ControlledUncontrolledDemo.jsx", startLine: 156, endLine: 168 }],
    },
    "mirror-controlled-prop": {
      id: "mirror-controlled-prop",
      title: "认为受控 prop 应复制进 local State 再用 Effect 同步",
      diagnosis: "这会制造两份同义当前值并引入同步顺序；受控模式应直接读取外部 value。",
      counterEvidence: "Tabs 用 activeValue = isControlled ? value : internalValue 明确只选择一个 authority。",
      experiment: "指出 value 与 internalValue 同时充当“当前值”时会出现哪些竞争路径。",
      evidenceRefs: [{ kind: "source", fileName: "ControlledUncontrolledDemo.jsx", startLine: 9, endLine: 18 }],
    },
  },
};
