export const EVENT_PROPAGATION_MODEL = {
  learningUnitId: "event-propagation",
  version: 1,
  mechanismTitle: "传播路径与浏览器默认行为是两条独立轴",
  mechanismAriaLabel: "Event propagation 与 default behavior 机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它负责什么",
    change: "调用控制 API 时",
  },
  contrastTitle: "stopPropagation 与 preventDefault 不解决同一个问题",
  codeEvidence: [
    {
      id: "target-controls-two-axes",
      title: "Target handler 独立控制默认行为与传播",
      explanation: "同一个 target handler 分别调用 preventDefault 与 stopPropagation；两个开关可以独立启用，因此它们表达的是两个不同维度。",
      sourceRef: { kind: "source", fileName: "EventPropagationDemo.jsx", startLine: 12, endLine: 22 },
    },
    {
      id: "capture-target-bubble-submit",
      title: "同一次点击同时经过传播链并可能触发默认提交",
      explanation: "父层注册 capture 与 bubble，按钮位于 form 内并拥有自己的 onClick。点击时要分别推理传播阶段和 submit 默认行为。",
      sourceRef: { kind: "source", fileName: "EventPropagationDemo.jsx", startLine: 45, endLine: 53 },
    },
  ],
  mechanismMap: [
    {
      id: "capture",
      label: "Capture",
      example: "onClickCapture",
      role: "事件到达 target 前，沿 React tree 从外向内观察。",
      change: "target 后调用 stopPropagation 不会撤销已经发生的 capture。",
    },
    {
      id: "target",
      label: "Target",
      example: "button onClick",
      role: "处理这次具体交互，可以决定是否阻止后续传播或默认行为。",
      change: "stopPropagation 与 preventDefault 可独立调用。",
    },
    {
      id: "bubble",
      label: "Bubble",
      example: "parent onClick",
      role: "事件从 target 向祖先继续传播。",
      change: "stopPropagation 会阻止后续 bubble handler。",
    },
    {
      id: "default-behavior",
      label: "Default behavior",
      example: "submit button → form submit",
      role: "浏览器对该交互的默认动作。",
      change: "preventDefault 可取消默认动作，但不会自动停止 bubble。",
    },
  ],
  contrastCases: [
    {
      id: "stop-propagation",
      title: "只 stopPropagation",
      keyStory: "capture 已经发生。",
      identityStory: "target handler 正常执行。",
      stateStory: "后续 parent bubble 被截断。",
      uiStory: "浏览器默认行为若未 prevent，仍可能发生。",
      conclusion: "它控制传播，不等于取消浏览器默认动作。",
    },
    {
      id: "prevent-default",
      title: "只 preventDefault",
      keyStory: "capture 正常发生。",
      identityStory: "target handler 正常执行。",
      stateStory: "parent bubble 仍继续。",
      uiStory: "浏览器默认提交/跳转被取消。",
      conclusion: "它控制默认行为，不等于停止传播。",
    },
  ],
  misconceptions: {
    "prevent-default-stops-bubble": {
      id: "prevent-default-stops-bubble",
      title: "认为 preventDefault 会阻止父级 onClick",
      diagnosis: "preventDefault 只取消浏览器默认动作，不改变 React 事件传播路径。",
      counterEvidence: "Demo 只开启 preventDefault 时，parent bubble 日志仍会出现，但 form submit 默认行为被取消。",
      experiment: "只勾选 preventDefault，再点击提交按钮；同时观察 parent bubble 与 form submit 日志。",
      evidenceRefs: [
        { kind: "source", fileName: "EventPropagationDemo.jsx", startLine: 12, endLine: 17 },
        { kind: "source", fileName: "EventPropagationDemo.jsx", startLine: 45, endLine: 53 },
      ],
    },
    "stop-propagation-prevents-default": {
      id: "stop-propagation-prevents-default",
      title: "认为 stopPropagation 会自动取消 submit / navigation",
      diagnosis: "stopPropagation 只影响事件向后续 handler 传播；默认行为是另一条浏览器语义。",
      counterEvidence: "Demo 把 stopBubble 与 preventDefault 做成两个独立开关，就是为了显示两条轴不能互换。",
      experiment: "只勾选 stopPropagation，比较 parent bubble 与 form submit 是否还会发生。",
      evidenceRefs: [{ kind: "source", fileName: "EventPropagationDemo.jsx", startLine: 12, endLine: 27 }],
    },
    "handler-called-in-render": {
      id: "handler-called-in-render",
      title: "把 onClick={handleClick()} 当成传递 handler",
      diagnosis: "带括号会在 render 时立即执行函数，React 得到的是调用结果而不是等待交互的函数。",
      counterEvidence: "Demo 使用 onClick={handleTargetClick}，函数只在按钮被点击时执行。",
      experiment: "对比 onClick={handleTargetClick} 与 onClick={handleTargetClick()} 的 JavaScript 求值时机。",
      evidenceRefs: [{ kind: "source", fileName: "EventPropagationDemo.jsx", startLine: 50, endLine: 53 }],
    },
  },
};
