export const IMMUTABLE_STATE_MODEL = {
  learningUnitId: "immutable-state",
  version: 1,
  mechanismTitle: "旧 State snapshot 保持可信，更新构造下一份值",
  mechanismAriaLabel: "Immutable State 更新机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它负责什么",
    change: "更新时",
  },
  contrastTitle: "新容器引用不代表嵌套对象也已经复制",
  codeEvidence: [
    {
      id: "nested-path-copy",
      title: "嵌套对象只复制发生变化的路径",
      explanation: "profile 更新时同时复制顶层对象和 address；未变化字段继续复用，而旧 snapshot 的 address 不被改写。",
      sourceRef: { kind: "source", fileName: "ImmutableStateDemo.jsx", startLine: 24, endLine: 30 },
    },
    {
      id: "same-reference-vs-copy",
      title: "同引用 mutation 与 copy + new reference 的直接对照",
      explanation: "错误路径先改写现有对象再 set 回同一引用；正确路径从 current 构造新对象。前者既可能跳过预期更新，也污染旧 snapshot。",
      sourceRef: { kind: "source", fileName: "ImmutableStateDemo.jsx", startLine: 32, endLine: 46 },
    },
  ],
  mechanismMap: [
    {
      id: "current-snapshot",
      label: "Current snapshot",
      example: "profile / tasks",
      role: "当前 render 读取到的 State 值。",
      change: "应按只读值处理，不能被下一次更新原地改写。",
    },
    {
      id: "next-value",
      label: "Next value",
      example: "{ ...current, ... }",
      role: "根据当前 snapshot 构造下一份 State。",
      change: "变化路径需要新对象/数组引用。",
    },
    {
      id: "shallow-copy",
      label: "Shallow copy",
      example: "[...items] / { ...obj }",
      role: "只复制当前这一层容器。",
      change: "嵌套对象仍可能与旧 snapshot 共享引用。",
    },
    {
      id: "setter",
      label: "Setter",
      example: "setProfile(next)",
      role: "把下一份值交给 React。",
      change: "同一引用可能被 Object.is 判为没有新的 State 值。",
    },
  ],
  contrastCases: [
    {
      id: "same-reference-mutation",
      title: "mutate + set 同一引用",
      keyStory: "旧对象已经被改写。",
      identityStory: "顶层引用仍相同。",
      stateStory: "历史 snapshot 不再可信。",
      uiStory: "这次更新可能被跳过，之后 render 又暴露被偷偷改写的数据。",
      conclusion: "问题不只是“React 看引用”，更是旧 State 被污染。",
    },
    {
      id: "copy-changed-path",
      title: "copy changed path",
      keyStory: "旧 snapshot 保持不变。",
      identityStory: "变化路径产生新引用。",
      stateStory: "新旧值边界清楚。",
      uiStory: "React 接收到下一份明确的 State 值。",
      conclusion: "复制应覆盖从变化节点到顶层的整条路径。",
    },
  ],
  misconceptions: {
    "new-array-is-deep-copy": {
      id: "new-array-is-deep-copy",
      title: "认为 [...items] 会深复制数组里的对象",
      diagnosis: "spread 只复制数组容器；元素对象仍与旧数组共享同一引用。",
      counterEvidence: "const next = [...items]; next[0].done = true 仍会改写旧 items[0] 指向的对象。",
      experiment: "比较 Object.is(items[0], [...items][0]) 的结果，再判断修改 next[0] 会影响谁。",
      evidenceRefs: [{ kind: "source", fileName: "ImmutableStateDemo.jsx", startLine: 48, endLine: 62 }],
    },
    "same-reference-set-is-safe": {
      id: "same-reference-set-is-safe",
      title: "认为 mutate 后 set 回同一对象只是另一种更新写法",
      diagnosis: "它先破坏了旧 snapshot，同时 setter 还可能因为引用相同而跳过这次更新。",
      counterEvidence: "Demo 专门提供 mutateSameReference 与无关 render，显示被污染的对象可能之后才暴露在 UI 中。",
      experiment: "依次点“错误：mutate + set 同引用”与“触发一次无关 render”，观察城市何时出现变化。",
      evidenceRefs: [{ kind: "source", fileName: "ImmutableStateDemo.jsx", startLine: 32, endLine: 39 }],
    },
    "copy-only-top-level": {
      id: "copy-only-top-level",
      title: "认为修改嵌套字段时只复制最外层就够了",
      diagnosis: "如果继续修改共享的 nested object，旧 snapshot 里的同一个对象也会被改写。",
      counterEvidence: "changeCity 同时复制 current 与 current.address，确保修改路径上的每一层都有新引用。",
      experiment: "对比 { ...profile, address: profile.address } 后直接改 address.city 与当前 Demo 的 nested copy。",
      evidenceRefs: [{ kind: "source", fileName: "ImmutableStateDemo.jsx", startLine: 24, endLine: 30 }],
    },
  },
};
