export const LIFTING_STATE_UP_MODEL = {
  learningUnitId: "lifting-state-up",
  version: 1,
  mechanismTitle: "共享事实只保留一份，由最近共同 owner 协调",
  mechanismAriaLabel: "Lifting State Up 数据所有权机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它负责什么",
    change: "query 改变时",
  },
  contrastTitle: "兄弟协同不需要横向同步，而需要一个共同事实来源",
  contrastDimensions: [
    { id: "ownerStory", label: "Owner" },
    { id: "dataStory", label: "数据流" },
    { id: "syncStory", label: "同步" },
    { id: "riskStory", label: "风险" },
  ],
  codeEvidence: [
    {
      id: "controlled-search-box",
      title: "SearchBox 只接收 value + onChange，不保存自己的 query",
      explanation: "输入框展示父级 value，并把用户输入通过 callback 向上报告；它不需要知道 Summary 或 List 的存在。",
      sourceRef: { kind: "source", fileName: "LiftingStateUpDemo.jsx", startLine: 7, endLine: 16 },
    },
    {
      id: "parent-owns-query",
      title: "最近共同父级保存 query，并从它派生 filteredList",
      explanation: "一个 query 同时驱动输入框、摘要和列表。共享事实只有一个 owner，因此多个子组件天然保持一致。",
      sourceRef: { kind: "source", fileName: "LiftingStateUpDemo.jsx", startLine: 137, endLine: 148 },
    },
  ],
  mechanismMap: [
    {
      id: "shared-fact",
      label: "Shared fact",
      example: "query",
      role: "多个兄弟组件都依赖的同一业务事实。",
      change: "只在一个 owner 中更新。",
    },
    {
      id: "owner",
      label: "Nearest common owner",
      example: "LiftingStateUpDemo",
      role: "保存权威 State 并协调消费者。",
      change: "新值通过 props 同时流向所有依赖者。",
    },
    {
      id: "value-flow",
      label: "Props down",
      example: "value={query}",
      role: "把当前事实传给子组件。",
      change: "下一次 render 所有消费者读取同一值。",
    },
    {
      id: "intent-flow",
      label: "Callbacks up",
      example: "onChange={setQuery}",
      role: "把用户意图送回 owner。",
      change: "owner 决定如何更新权威值。",
    },
  ],
  contrastCases: [
    {
      id: "duplicate-local-state",
      title: "兄弟各存一份同义 State",
      ownerStory: "没有唯一 owner。",
      dataStory: "每个子组件都有自己的 query。",
      syncStory: "需要额外回调/Effect 互相同步。",
      riskStory: "任何漏同步都会出现不同 UI 事实。",
      conclusion: "横向同步通常暴露了重复事实。",
    },
    {
      id: "lifted-state",
      title: "提升到最近共同 owner",
      ownerStory: "父级保存唯一 query。",
      dataStory: "props 向下、callback 向上。",
      syncStory: "所有消费者自然读取同一 render 输入。",
      riskStory: "无需维护兄弟间第二条同步通道。",
      conclusion: "提升的目标是协调范围恰好覆盖真实消费者，而不是越高越好。",
    },
  ],
  misconceptions: {
    "siblings-should-sync": {
      id: "siblings-should-sync",
      title: "认为兄弟组件应该互相 setState 保持一致",
      diagnosis: "同一事实被保存多份才需要横向同步；应先建立一个共同 owner。",
      counterEvidence: "Demo 的 SearchBox、Summary、List 都只围绕父级 query 协同，没有兄弟互相调用。",
      experiment: "输入搜索词，追踪 query 从 SearchBox callback 到父级，再通过 props 到三个消费者。",
      evidenceRefs: [
        { kind: "source", fileName: "LiftingStateUpDemo.jsx", startLine: 7, endLine: 16 },
        { kind: "source", fileName: "LiftingStateUpDemo.jsx", startLine: 137, endLine: 148 },
      ],
    },
    "lift-to-root": {
      id: "lift-to-root",
      title: "认为 State 提升就是放到 App 最顶层",
      diagnosis: "owner 只需覆盖必须协调的消费者；过度提升会扩大依赖面并增加样板。",
      counterEvidence: "Demo 把 query 放在 SearchBox、Summary、List 的最近共同父级，而不是全局根节点。",
      experiment: "标出真正读取 query 的组件，找出能同时覆盖它们的最近共同祖先。",
      evidenceRefs: [{ kind: "source", fileName: "LiftingStateUpDemo.jsx", startLine: 137, endLine: 148 }],
    },
    "callback-is-child-write": {
      id: "callback-is-child-write",
      title: "认为 onChange 让子组件直接修改父级 State",
      diagnosis: "callback 表达用户意图；owner 仍可以校验、转换或拒绝。",
      counterEvidence: "SearchBox 只调用 onChange(value)，它并不持有 query。",
      experiment: "把 onChange 替换成一个会规范化输入的父级 handler，观察 authority 仍在父级。",
      evidenceRefs: [{ kind: "source", fileName: "LiftingStateUpDemo.jsx", startLine: 7, endLine: 16 }],
    },
  },
};
