export const MULTI_SLOTS_MODEL = {
  learningUnitId: "multi-slots",
  version: 1,
  mechanismTitle: "具名插槽首先是一份明确的三态 API 协议",
  mechanismAriaLabel: "Named slots 三态协议",
  mechanismHeaders: {
    subject: "输入状态",
    example: "title / footer",
    role: "组件如何解释",
    change: "渲染结果",
  },
  contrastTitle: "undefined、custom 与 false 必须保持可区分",
  codeEvidence: [
    {
      id: "header-three-state",
      title: "Header 的三态判断顺序",
      explanation: "先判断 false 显式隐藏，再判断 !== undefined 作为调用者覆盖，最后才回退默认模板；如果用简单 truthy 判断就会把这些语义压扁。",
      sourceRef: { kind: "source", fileName: "ProductionModal.jsx", startLine: 80, endLine: 94 },
    },
    {
      id: "footer-three-state",
      title: "Footer 使用同一协议",
      explanation: "footer=false 不渲染区域；自定义 JSX 进入覆盖分支；只有 undefined 才使用 DefaultModalFooter。",
      sourceRef: { kind: "source", fileName: "ProductionModal.jsx", startLine: 96, endLine: 106 },
    },
  ],
  mechanismMap: [
    {
      id: "undefined",
      label: "未提供",
      example: "footer === undefined",
      role: "调用者接受组件内置默认。",
      change: "渲染默认 Footer。",
    },
    {
      id: "override",
      label: "显式覆盖",
      example: "footer={<Actions />}",
      role: "调用者提供自己的区域内容。",
      change: "渲染自定义 slot。",
    },
    {
      id: "hidden",
      label: "显式隐藏",
      example: "footer={false}",
      role: "调用者明确要求该区域不存在。",
      change: "返回 null，不回退默认模板。",
    },
    {
      id: "children",
      label: "主体插槽",
      example: "children",
      role: "承载 Modal 主内容。",
      change: "独立于 header/footer 协议组合。",
    },
  ],
  contrastCases: [
    {
      id: "fallback-default",
      title: "什么都不传",
      keyStory: "slot prop 为 undefined。",
      identityStory: "调用者没有覆盖意图。",
      stateStory: "组件采用自己的默认策略。",
      uiStory: "默认 header/footer 出现。",
      conclusion: "缺省值与“隐藏”是不同产品语义。",
    },
    {
      id: "explicit-hide",
      title: "传 false",
      keyStory: "调用者明确关闭该区域。",
      identityStory: "协议必须保留这个信号。",
      stateStory: "不能被 || 默认值吃掉。",
      uiStory: "该区域完全不渲染。",
      conclusion: "三态 API 需要精确比较，而不是泛化 falsy。",
    },
  ],
  misconceptions: {
    "falsy-collapse": {
      id: "falsy-collapse",
      title: "用 slot || default 实现三态协议",
      diagnosis: "|| 会把 false 与 undefined 都视为需要 fallback，导致“显式隐藏”失效。",
      counterEvidence: "当前 ProductionModal 对 false 单独返回 null，只有 undefined 才进入默认模板。",
      experiment: "打开“显式隐藏底部”场景，确认 footer=false 后没有默认按钮栏。",
      evidenceRefs: [{ kind: "source", fileName: "ProductionModal.jsx", startLine: 96, endLine: 106 }],
    },
    "false-means-default": {
      id: "false-means-default",
      title: "认为 false 等于没有传值",
      diagnosis: "在这份组件 API 中，false 是调用者主动选择“不要这个区域”的业务信号。",
      counterEvidence: "Demo 的 no-footer 场景显式传 footer={false}，结果与省略 footer 完全不同。",
      experiment: "对比“全默认模板”和“显式隐藏底部”两个按钮打开后的 Modal。",
      evidenceRefs: [{ kind: "source", fileName: "MultiSlotsDemo.jsx", startLine: 77, endLine: 89 }],
    },
    "named-slot-is-context": {
      id: "named-slot-is-context",
      title: "把具名插槽理解成 Context",
      diagnosis: "具名 slot 仍是普通 props 传递的 React node；它不建立跨层订阅或隐式读取。",
      counterEvidence: "ProductionModal 的 title/footer 都直接出现在函数参数中，调用者在 JSX 上显式传值。",
      experiment: "定位 ProductionModal 参数列表和一个自定义 footer 的调用点。",
      evidenceRefs: [{ kind: "source", fileName: "ProductionModal.jsx", startLine: 70, endLine: 77 }],
    },
  },
};
