export const PROP_DRILLING_MODEL = {
  learningUnitId: "prop-drilling",
  version: 1,
  mechanismTitle: "先问数据归谁、谁消费，再决定传递机制",
  mechanismAriaLabel: "Props composition context 选择机制",
  mechanismHeaders: {
    subject: "机制",
    example: "当前 Demo",
    role: "适合什么关系",
    change: "主要代价",
  },
  contrastTitle: "Props、Composition、Context 都能工作，区别在依赖边界",
  codeEvidence: [
    {
      id: "composition-layout-slot",
      title: "中间层只负责布局时可以不认识 user",
      explanation: "CompositionNavbar 只声明 rightSlot 的布局位置；调用者已经把需要 user 的 Avatar 组装好，所以 Navbar 不再承担机械透传。",
      sourceRef: { kind: "source", fileName: "PropDrillingDemo.jsx", startLine: 99, endLine: 110 },
    },
    {
      id: "context-consumer",
      title: "真正消费者可以直接订阅 Context",
      explanation: "ContextAvatar 用 useContext 读取当前 Provider value；这减少中间 props，但同时让依赖从 JSX 调用参数变成 Context 订阅。",
      sourceRef: { kind: "source", fileName: "PropDrillingDemo.jsx", startLine: 119, endLine: 145 },
    },
  ],
  mechanismMap: [
    {
      id: "props",
      label: "Props",
      example: "Navbar → Header → Avatar",
      role: "局部、显式地把数据沿调用关系传下去。",
      change: "链路很深且中间层不消费时会产生接口噪声。",
    },
    {
      id: "composition",
      label: "Composition",
      example: "rightSlot",
      role: "让布局容器接收已组装好的 JSX，而不是理解业务数据。",
      change: "父级承担更多结构组合职责。",
    },
    {
      id: "context",
      label: "Context",
      example: "UserContext",
      role: "让远距离、多处消费者读取同一环境式依赖。",
      change: "依赖更隐式，Provider value 更新会传播到消费者。",
    },
    {
      id: "ownership",
      label: "State ownership",
      example: "PropDrillingDemo.user",
      role: "决定谁能真正更新这份数据。",
      change: "传递机制不会自动改变数据所有权。",
    },
  ],
  contrastCases: [
    {
      id: "few-explicit-consumers",
      title: "少量清晰消费链",
      keyStory: "数据来源容易追踪。",
      identityStory: "组件 API 显式。",
      stateStory: "所有权不变。",
      uiStory: "继续 props 往往最简单。",
      conclusion: "不要为了“层数”本身消灭 Props。",
    },
    {
      id: "many-distant-consumers",
      title: "多个远距离消费者",
      keyStory: "中间层长期不消费数据。",
      identityStory: "Context 表达共享环境依赖。",
      stateStory: "Provider 仍是 value 来源。",
      uiStory: "消费者直接 useContext。",
      conclusion: "Context 是依赖模型选择，不是少写几个参数的语法糖。",
    },
  ],
  misconceptions: {
    "any-depth-is-drilling": {
      id: "any-depth-is-drilling",
      title: "看到两三层 Props 就立即判定为反模式",
      diagnosis: "Props 的显式性本身有价值；只有大量中间组件长期机械透传时才形成真实设计成本。",
      counterEvidence: "Demo 同时保留 props 路径，并明确把它作为可工作的基线而非错误代码。",
      experiment: "观察 Navbar/Header 是否真的需要 user；再判断引入另一机制能解决什么具体成本。",
      evidenceRefs: [{ kind: "source", fileName: "PropDrillingDemo.jsx", startLine: 35, endLine: 74 }],
    },
    "context-default-choice": {
      id: "context-default-choice",
      title: "认为 Context 是跨组件数据的默认方案",
      diagnosis: "Context 会隐藏部分依赖来源并建立订阅关系；它适合真正的跨层共享，而不是所有父子通信。",
      counterEvidence: "只有 ContextAvatar 调用 useContext，中间层虽然更干净，但依赖也不再出现在组件调用参数上。",
      experiment: "比较 DrillingAvatar 的 user prop 与 ContextAvatar 的 useContext，指出依赖在代码中的可见位置。",
      evidenceRefs: [{ kind: "source", fileName: "PropDrillingDemo.jsx", startLine: 119, endLine: 145 }],
    },
    "composition-changes-ownership": {
      id: "composition-changes-ownership",
      title: "认为 Composition 会把数据所有权移给容器",
      diagnosis: "slot/children 只改变结构传递路径；user 仍由原来的上层 State 所有者管理。",
      counterEvidence: "CompositionNavbar 收到的是已组装的 rightSlot，它既不读取 user 也不拥有 user State。",
      experiment: "修改顶层 user 输入，观察 Composition 路径仍然更新，然后定位真正的 setUser。",
      evidenceRefs: [{ kind: "source", fileName: "PropDrillingDemo.jsx", startLine: 190, endLine: 198 }],
    },
  },
};
