export const PROPS_MODEL = {
  learningUnitId: "props",
  version: 1,
  mechanismTitle: "Props 是父级给当前 render 的只读输入",
  mechanismAriaLabel: "Props 数据流机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它负责什么",
    change: "输入变化时",
  },
  contrastTitle: "默认值、派生值与复制 State 是三件不同的事",
  codeEvidence: [
    {
      id: "props-default-destructure",
      title: "默认值发生在参数读取边界",
      explanation: "UserCard 直接从 props 解构输入；role 只有在对应值为 undefined 时才使用“普通成员”默认值。",
      sourceRef: { kind: "source", fileName: "UserCard.jsx", startLine: 5, endLine: 7 },
    },
    {
      id: "derive-from-props",
      title: "能从 Props 算出的值不必再复制一份 State",
      explanation: "ProductCard 每次 render 直接用 price × discount 得到 actualPrice，使显示值天然跟随当前 props，而无需额外同步。",
      sourceRef: { kind: "source", fileName: "ProductCard.jsx", startLine: 5, endLine: 9 },
    },
  ],
  mechanismMap: [
    {
      id: "owner",
      label: "数据所有者",
      example: "PropsBasicsDemo State",
      role: "保存并更新 userName / price 等源数据。",
      change: "所有者更新后触发新的 render。",
    },
    {
      id: "props-input",
      label: "Props",
      example: "name / role / price",
      role: "父级把当前值传给子组件的只读输入。",
      change: "子组件下一次 render 读取新值，而不是修改旧 props。",
    },
    {
      id: "derived-value",
      label: "派生值",
      example: "actualPrice",
      role: "由当前 props 直接计算出的显示数据。",
      change: "源 props 一变，下一次 render 自动重新计算。",
    },
    {
      id: "child-output",
      label: "子组件 JSX",
      example: "UserCard / ProductCard",
      role: "根据当前输入生成 UI 描述。",
      change: "不需要复制一份 props State 来保持同步。",
    },
  ],
  contrastCases: [
    {
      id: "omitted-default",
      title: "省略 role",
      keyStory: "role === undefined。",
      identityStory: "组件身份不因此改变。",
      stateStory: "参数默认值生效。",
      uiStory: "显示“普通成员”。",
      conclusion: "默认参数处理缺省输入，不是新的 State。",
    },
    {
      id: "derived-price",
      title: "price / discount 更新",
      keyStory: "父级提供新的输入值。",
      identityStory: "同一 ProductCard 可以继续 render。",
      stateStory: "actualPrice 直接重新计算。",
      uiStory: "售价立即反映当前输入。",
      conclusion: "可派生数据无需用 Effect 再同步。",
    },
  ],
  misconceptions: {
    "props-owned-by-child": {
      id: "props-owned-by-child",
      title: "认为子组件可以修改收到的 Props",
      diagnosis: "Props 是父级提供给本次 render 的输入；子组件要请求变化，应通过 callback/上层状态所有者表达。",
      counterEvidence: "Demo 中输入控件更新的是父组件 State，UserCard 只读取下一次传入的新 props。",
      experiment: "修改父级控制面板的姓名，再观察 UserCard 更新；定位 setUserName 在哪个组件里。",
      evidenceRefs: [{ kind: "source", fileName: "PropsBasicsDemo.jsx", startLine: 70, endLine: 108 }],
    },
    "default-applies-to-null": {
      id: "default-applies-to-null",
      title: "认为解构默认值会替换 null",
      diagnosis: "JavaScript 参数/解构默认值只在值为 undefined 时生效；显式 null 是一个真实传入值。",
      counterEvidence: "UserCard 的 role = “普通成员”遵循 JavaScript 默认参数语义，不是 React 的 falsy 回退规则。",
      experiment: "对比省略 role、role={undefined} 与 role={null} 的 JavaScript 参数结果。",
      evidenceRefs: [{ kind: "source", fileName: "UserCard.jsx", startLine: 5, endLine: 7 }],
    },
    "derived-value-needs-state": {
      id: "derived-value-needs-state",
      title: "认为计算值必须再存成 State",
      diagnosis: "如果值能完全由当前 props/state 推导，复制一份 State 会制造同步责任。",
      counterEvidence: "ProductCard 的 actualPrice 每次直接由 price × discount 得到，不存在额外同步路径。",
      experiment: "改变 price / discount，观察 actualPrice 不需要 setter 也会随 render 更新。",
      evidenceRefs: [{ kind: "source", fileName: "ProductCard.jsx", startLine: 5, endLine: 9 }],
    },
  },
};
