export const RENDER_COMMIT_MODEL = {
  learningUnitId: "render-commit",
  version: 1,
  mechanismTitle: "Trigger、Render、Commit、Browser Paint 分属不同层级",
  mechanismAriaLabel: "Render Commit 生命周期机制区分",
  mechanismHeaders: {
    subject: "阶段",
    example: "当前 Demo",
    role: "它负责什么",
    change: "是否意味着 Count DOM 改变",
  },
  contrastTitle: "组件更新与特定 DOM mutation 不是一一对应",
  codeEvidence: [
    {
      id: "two-update-triggers",
      title: "两个 State 更新都能触发 React 工作",
      explanation: "一个更新 count，一个只更新 themeTick。两者都请求新的 React render，但只有前者会改变 Count 文本。",
      sourceRef: { kind: "source", fileName: "RenderCommitDemo.jsx", startLine: 42, endLine: 50 },
    },
    {
      id: "observed-count-node",
      title: "同一个渲染结果里只观察 Count 节点是否真的 mutation",
      explanation: "两个按钮分别触发不同 State 更新，Count 节点与 themeTick 分开显示；MutationObserver 只验证 Count DOM 是否有真实变化。",
      sourceRef: { kind: "source", fileName: "RenderCommitDemo.jsx", startLine: 63, endLine: 70 },
    },
  ],
  mechanismMap: [
    {
      id: "trigger",
      label: "Trigger",
      example: "setCount / setThemeTick",
      role: "让 React 安排一次新的更新工作。",
      change: "只说明有更新请求，不保证某个 DOM 节点会变。",
    },
    {
      id: "render",
      label: "Render",
      example: "调用组件计算 JSX",
      role: "根据当前输入计算下一份 UI 描述。",
      change: "组件可以 render，而目标 DOM 最终无需 mutation。",
    },
    {
      id: "commit",
      label: "Commit",
      example: "应用必要 host changes",
      role: "把 reconciliation 确认需要的变化提交给宿主环境。",
      change: "只有确实需要的 DOM/refs 等变化才会应用。",
    },
    {
      id: "paint",
      label: "Browser Paint",
      example: "浏览器布局/绘制",
      role: "浏览器在 DOM 变化后安排像素绘制。",
      change: "它不是 React render phase，也不是 commit callback。",
    },
  ],
  contrastCases: [
    {
      id: "count-update",
      title: "更新 count",
      keyStory: "State update 触发工作。",
      identityStory: "组件重新计算下一份 UI。",
      stateStory: "Count 文本从旧值变成新值。",
      uiStory: "Commit 需要修改 Count DOM。",
      conclusion: "这里能观察到目标 DOM mutation。",
    },
    {
      id: "unrelated-update",
      title: "只更新 themeTick",
      keyStory: "同样产生 State update。",
      identityStory: "组件仍可重新 render。",
      stateStory: "Count 文本计算结果保持不变。",
      uiStory: "Count DOM 无需 mutation。",
      conclusion: "render 并不意味着每个 DOM 节点都更新。",
    },
  ],
  misconceptions: {
    "render-equals-dom-mutation": {
      id: "render-equals-dom-mutation",
      title: "认为组件 render 一次就必然修改对应 DOM",
      diagnosis: "Render 只计算下一份 UI；commit 只应用真正需要的 host changes。",
      counterEvidence: "只更新 themeTick 时组件参与更新，但 MutationObserver 可以观察到 Count 节点没有 mutation。",
      experiment: "分别点击“更新 count”和“只更新无关 state”，只比较 Count 节点的观察结果。",
      evidenceRefs: [
        { kind: "source", fileName: "RenderCommitDemo.jsx", startLine: 42, endLine: 50 },
        { kind: "source", fileName: "RenderCommitDemo.jsx", startLine: 63, endLine: 70 },
      ],
    },
    "raf-is-commit-callback": {
      id: "raf-is-commit-callback",
      title: "把 requestAnimationFrame 当成 React commit callback",
      diagnosis: "rAF 属于浏览器帧调度，只能在后续浏览器帧做观察，不能告诉你 React 内部 commit 的精确时刻。",
      counterEvidence: "Demo 明确用 rAF 只给“未观察到 Count mutation”收尾，而不是统计 React render/commit。",
      experiment: "阅读 observeNextBrowserFrame，指出它读取的是 mutationSeenRef，而不是 React 提供的 commit 事件。",
      evidenceRefs: [{ kind: "source", fileName: "RenderCommitDemo.jsx", startLine: 28, endLine: 40 }],
    },
    "paint-is-react-render": {
      id: "paint-is-react-render",
      title: "把浏览器 Paint 与 React Render 混为一谈",
      diagnosis: "React render 是 JavaScript UI 计算；浏览器 paint 是宿主环境在 DOM/layout 后绘制像素。",
      counterEvidence: "Demo 的四阶段说明把 Browser Paint 单独列在 Commit 之后，并说明其时机由浏览器调度。",
      experiment: "把 Trigger、Render、Commit、Paint 分别归类到 React 计算、React 宿主提交和浏览器绘制。",
      evidenceRefs: [{ kind: "source", fileName: "RenderCommitDemo.jsx", startLine: 74, endLine: 83 }],
    },
  },
};
