export const STATE_REDUCER_MODEL = {
  learningUnitId: "state-reducer",
  version: 1,
  mechanismTitle: "Event 描述发生了什么，Reducer 纯计算下一份 State",
  mechanismAriaLabel: "useReducer 状态转换机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它负责什么",
    change: "dispatch 后",
  },
  contrastTitle: "把事件边界的非确定输入与 reducer 的纯转换分开",
  contrastDimensions: [
    { id: "eventStory", label: "事件边界" },
    { id: "actionStory", label: "Action" },
    { id: "reducerStory", label: "Reducer" },
    { id: "stateStory", label: "State" },
  ],
  codeEvidence: [
    {
      id: "pure-transition",
      title: "Reducer 只读取 state + action 并返回 next state",
      explanation: "INCREMENT 使用当前 state 与 action.at 计算下一份值；时间不是在 reducer 内读取，因此相同输入保持确定性。",
      sourceRef: { kind: "source", fileName: "StateReducerDemo.jsx", startLine: 16, endLine: 25 },
    },
    {
      id: "event-boundary-action-data",
      title: "非确定性时间在事件边界产生，再放进 action",
      explanation: "dispatchWithTimestamp 在 handler 路径读取当前时间并发送 action；reducer 只消费这个已明确的数据。",
      sourceRef: { kind: "source", fileName: "StateReducerDemo.jsx", startLine: 67, endLine: 72 },
    },
  ],
  mechanismMap: [
    {
      id: "event",
      label: "Event Handler",
      example: "dispatchWithTimestamp",
      role: "接收用户动作并准备事件数据。",
      change: "可以读取时间等非确定输入。",
    },
    {
      id: "action",
      label: "Action",
      example: "{ type, at }",
      role: "描述发生了什么以及转换需要的数据。",
      change: "被送入 reducer。",
    },
    {
      id: "reducer",
      label: "Reducer",
      example: "counterReducer(state, action)",
      role: "纯函数计算 next State。",
      change: "不做网络、时间读取或其他副作用。",
    },
    {
      id: "next-state",
      label: "Next State",
      example: "return { ...state, count }",
      role: "下一次 render 的权威状态。",
      change: "dispatch 不会同步改写当前 render 已读到的 state。",
    },
  ],
  contrastCases: [
    {
      id: "impure-reducer",
      title: "Reducer 内读取时间 / 发请求",
      eventStory: "事件边界没有收集完整输入。",
      actionStory: "action 缺少转换真正需要的数据。",
      reducerStory: "相同 state/action 可能得到不同结果或产生副作用。",
      stateStory: "难测试、难重放、开发检查可重复触发问题。",
      conclusion: "Reducer 的价值来自确定性转换，不是把所有逻辑搬进一个函数。",
    },
    {
      id: "pure-reducer",
      title: "事件收集输入，Reducer 只转换",
      eventStory: "handler 产生时间等外部输入。",
      actionStory: "action 携带完整事实。",
      reducerStory: "state + action → next state。",
      stateStory: "转换可独立测试和审计。",
      conclusion: "事件与转换职责分离后，复杂更新规则才真正更清楚。",
    },
  ],
  misconceptions: {
    "reducer-can-do-side-effects": {
      id: "reducer-can-do-side-effects",
      title: "认为 reducer 是集中放所有业务逻辑的地方",
      diagnosis: "Reducer 只应做纯 State 转换；网络、存储、时间等副作用留在事件或其他边界。",
      counterEvidence: "Demo 明确在 dispatchWithTimestamp 读取时间，再把 at 传给 reducer。",
      experiment: "把 Date.now()/new Date() 放进 reducer，问相同 state/action 重放时结果是否仍确定。",
      evidenceRefs: [{ kind: "source", fileName: "StateReducerDemo.jsx", startLine: 67, endLine: 72 }],
    },
    "dispatch-mutates-current-state": {
      id: "dispatch-mutates-current-state",
      title: "认为 dispatch 后当前 handler 里的 state 变量会立刻变",
      diagnosis: "dispatch 请求下一次 State；当前 render 的 snapshot 不会被同步改写。",
      counterEvidence: "useReducer 与 useState 一样遵守 render snapshot 模型。",
      experiment: "在同一 handler 中 dispatch 后立即记录当前 state.count，并区分 current snapshot 与 next render。",
      evidenceRefs: [{ kind: "source", fileName: "StateReducerDemo.jsx", startLine: 67, endLine: 72 }],
    },
    "object-state-requires-reducer": {
      id: "object-state-requires-reducer",
      title: "认为 State 是对象或字段多就必须 useReducer",
      diagnosis: "真正信号是相关转换规则、事件语义和独立测试价值，而不是数据类型。",
      counterEvidence: "Demo 说明简单更新仍可使用 useState；Reducer 解决的是转换组织方式。",
      experiment: "比较一个独立 boolean 与多条共享转换规则的状态，判断哪一个更需要 reducer。",
      evidenceRefs: [{ kind: "source", fileName: "StateReducerDemo.jsx", startLine: 67, endLine: 72 }],
    },
  },
};
