export const STATE_SNAPSHOT_QUEUE_MODEL = {
  learningUnitId: "state-snapshot-queue",
  version: 1,
  mechanismTitle: "先区分当前快照、更新请求和下一次 render",
  mechanismAriaLabel: "State Snapshot 与 Update Queue 机制区分",
  mechanismHeaders: {
    subject: "机制",
    example: "当前 Demo",
    role: "它负责什么",
    change: "同一次事件里会怎样",
  },
  contrastTitle: "三种队列，不要只看最后数字",
  contrastDimensions: [
    { id: "handlerStory", label: "当前 handler" },
    { id: "queueStory", label: "入队内容" },
    { id: "processingStory", label: "queue processing" },
    { id: "resultStory", label: "next render" },
  ],
  mechanismMap: [
    {
      id: "render-snapshot",
      label: "Render Snapshot",
      example: "count",
      role: "当前 render 已经得到的固定 State 值；事件 handler 读取的是这份快照。",
      change: "调用 setter 不会回头改写这份 count；当前 handler 后续读取仍看到同一 snapshot。",
    },
    {
      id: "update-request",
      label: "Update Request",
      example: "setCount(...)",
      role: "请求 React 为后续 render 计算新的 State，而不是直接修改当前变量。",
      change: "同一事件里的多个 setter 会形成一组待处理更新。",
    },
    {
      id: "replace-update",
      label: "Replace Update",
      example: "setCount(count + 1)",
      role: "先用当前 snapshot 计算一个具体值，再把“替换为这个值”的请求加入队列。",
      change: "count = 0 时连续三次都读取 0，因此三项都是 replace 1。",
    },
    {
      id: "updater-function",
      label: "Updater Function",
      example: "setCount(n => n + 1)",
      role: "把一个转换函数加入队列；React 处理队列时把上一项 pending state 传给它。",
      change: "三个 updater 会依次看到 0、1、2，并计算出 1、2、3。",
    },
    {
      id: "update-queue",
      label: "Update Queue",
      example: "replace → updater → replace",
      role: "按入队顺序处理本轮 State 更新，持续维护一个 pending state。",
      change: "replace 会直接设置 pending；updater 基于当前 pending 继续计算；后续 replace 还能再次覆盖 pending。",
    },
    {
      id: "next-render-state",
      label: "Next Render State",
      example: "scenario.result",
      role: "队列处理结束后的最终 pending value，会成为下一次 render 的 State。",
      change: "下一次 render 才拿到新的 snapshot；它与当前 handler 内仍在读取的旧 snapshot 是两回事。",
    },
  ],
  contrastCases: [
    {
      id: "replace-three",
      title: "Replace × 3",
      handlerStory: "当前 snapshot 是 0，三次表达式里的 count 都读取 0。",
      queueStory: "replace 1 → replace 1 → replace 1",
      processingStory: "pending 被设为 1，再设为 1，再设为 1。",
      resultStory: "下一次 render 得到 1。",
      conclusion: "调用了三次不等于基于前一次结果累加三次；三个 replace 值都来自同一份 snapshot。",
    },
    {
      id: "updater-three",
      title: "Updater × 3",
      handlerStory: "当前 snapshot 仍是 0；handler 本身不会看到 1、2、3。",
      queueStory: "+1 updater → +1 updater → +1 updater",
      processingStory: "pending 依次 0 → 1 → 2 → 3。",
      resultStory: "下一次 render 得到 3。",
      conclusion: "updater 的关键不是“更异步”，而是它基于 queue 中前一项的 pending state 继续计算。",
    },
    {
      id: "mixed-queue",
      title: "Replace + Updater + Replace 42",
      handlerStory: "所有直接读取 count 的表达式仍基于同一当前 snapshot。",
      queueStory: "replace count+5 → +1 updater → replace 42",
      processingStory: "先得到 count+5，再由 updater 得到 count+6，最后 replace 把 pending 设置为 42。",
      resultStory: "下一次 render 得到 42。",
      conclusion: "结果是 42 不代表 React 只保留最后一次调用；队列按顺序处理，只是最后一个 replace 改写了 pending。",
    },
  ],
  misconceptions: {
    "setter-mutates-snapshot": {
      id: "setter-mutates-snapshot",
      title: "认为 setter 会立即修改当前 render 里的 State 变量",
      diagnosis: "这里把“请求下一次 State”误解成了“改写当前 handler 已经读取到的 snapshot”。",
      counterEvidence: "Demo 会同时展示 handler snapshot 和 next render state：它们可以不同，说明 setter 没有回头改写当前 snapshot。",
      experiment: "Reset 后点击 Replace × 3。对比 Queue Debugger 的 handler snapshot 与 next render state：前者仍是 0，后者是 1。",
      evidenceRefs: [
        { kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 22, endLine: 27 },
        { kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 105, endLine: 127 },
      ],
    },
    "repeated-replace-accumulates": {
      id: "repeated-replace-accumulates",
      title: "认为三次 setCount(count + 1) 会自动基于前一次结果继续 +1",
      diagnosis: "三个表达式都在同一个 handler 中读取同一份 count snapshot，因此它们计算的是同一个 replacement value。",
      counterEvidence: "count = 0 时 Queue Debugger 明确显示三个 replace 都是 1，而下一次 render 只得到 1。",
      experiment: "Reset → Replace × 3；逐条读 Queue Debugger，确认三项都是 replace 1，而不是 1、2、3。",
      evidenceRefs: [{ kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 29, endLine: 45 }],
    },
    "updater-is-syntax-sugar": {
      id: "updater-is-syntax-sugar",
      title: "认为 updater function 只是 setCount(count + 1) 的另一种语法",
      diagnosis: "updater 会在 React 处理队列时接收当前 pending state；直接 replace 则把调用时已经算好的具体值入队。",
      counterEvidence: "同样连续调用三次，Replace × 3 从 0 得到 1，而 Updater × 3 得到 3。",
      experiment: "Reset 后分别运行 Replace × 3 和 Updater × 3，对比 Queue Debugger 的每一步输入值。",
      evidenceRefs: [
        { kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 29, endLine: 45 },
        { kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 47, endLine: 63 },
      ],
    },
    "queue-keeps-last-only": {
      id: "queue-keeps-last-only",
      title: "认为 batching 会让 React 只保留最后一次 setter",
      diagnosis: "batching 并不等于丢弃前面的更新；React 仍按顺序处理 queue 中的 replace 与 updater。",
      counterEvidence: "从 count = 0 运行 Replace + Updater 会得到 6；如果只保留最后一个 +1 updater，结果不会是 6。",
      experiment: "Reset → Replace + Updater。观察 debugger 先 replace 5，再执行 +1 updater 得到 6。",
      evidenceRefs: [{ kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 65, endLine: 79 }],
    },
    "same-result-same-semantics": {
      id: "same-result-same-semantics",
      title: "认为最终数字相同就代表更新语义相同",
      diagnosis: "单个 replace count+3 和三个 updater 在某个起点可以得到相同结果，但它们进入 queue 的内容与组合方式并不相同。",
      counterEvidence: "updater 会消费前一项 pending state，因此当它与其他更新混排时，行为取决于 queue 顺序；replace 是已经算好的具体值。",
      experiment: "先观察 Updater × 3 的 0→1→2→3，再观察 Replace + Updater，确认 updater 会接住前一项 pending，而不是重新读取 handler snapshot。",
      evidenceRefs: [
        { kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 47, endLine: 79 },
      ],
    },
    "last-result-means-last-only": {
      id: "last-result-means-last-only",
      title: "看到最终 42 就认为前面的 queue 项没有执行",
      diagnosis: "最后一个 replace 42 会把当时的 pending state 改成 42，但这不等于前面的 replace / updater 从未被处理。",
      counterEvidence: "Queue Debugger 会列出 count+5 和 +1 updater 的中间步骤，然后才显示 replace 42。",
      experiment: "运行 Replace + Updater + Replace 42，逐行查看 debugger；确认 42 是最后一步覆盖 pending 的结果。",
      evidenceRefs: [{ kind: "source", fileName: "StateSnapshotQueueDemo.jsx", startLine: 81, endLine: 98 }],
    },
  },
};
