export const STATE_DRY_MODEL = {
  learningUnitId: "state-dry",
  version: 1,
  mechanismTitle: "先区分独立事实、派生值与重复事实",
  mechanismAriaLabel: "State 结构设计机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它表达什么",
    change: "设计影响",
  },
  contrastTitle: "好的 State shape 会让一部分错误状态根本无法表示",
  contrastDimensions: [
    { id: "sourceStory", label: "事实来源" },
    { id: "syncStory", label: "同步负担" },
    { id: "invalidStory", label: "错误状态" },
    { id: "designStory", label: "设计结果" },
  ],
  codeEvidence: [
    {
      id: "derived-vs-stored-name",
      title: "同一姓名：重复 State 与 render-time 派生并存",
      explanation: "firstName / lastName 是独立事实；derivedFullName 可直接由它们计算。额外保存 storedFullName 会新增一条必须人工维护的一致性约束。",
      sourceRef: { kind: "source", fileName: "StateDryDemo.jsx", startLine: 45, endLine: 54 },
    },
    {
      id: "selected-id-vs-copy",
      title: "保存 selectedId，而不是再保存一份实体副本",
      explanation: "cartItems 是 canonical collection。selectedId 是独立选择事实，而 selectedItem 可以从 collection + id 派生；selectedCopy 则可能过期。",
      sourceRef: { kind: "source", fileName: "StateDryDemo.jsx", startLine: 56, endLine: 63 },
    },
  ],
  mechanismMap: [
    {
      id: "independent-fact",
      label: "Independent fact",
      example: "firstName / selectedId",
      role: "用户或业务真正独立决定的信息。",
      change: "适合保存为 State。",
    },
    {
      id: "derived-value",
      label: "Derived value",
      example: "derivedFullName / selectedItem",
      role: "能由当前 props/state 完整计算出的值。",
      change: "直接在 render 派生，避免第二份事实。",
    },
    {
      id: "duplicate-state",
      label: "Duplicated State",
      example: "storedFullName / selectedCopy",
      role: "重复表达其他 State 已经拥有的事实。",
      change: "新增同步路径，容易 stale。",
    },
    {
      id: "exclusive-status",
      label: "Exclusive status",
      example: "status = typing | sending | sent",
      role: "把互斥业务阶段限制在合法集合。",
      change: "比多个松散 boolean 更少非法组合。",
    },
  ],
  contrastCases: [
    {
      id: "store-derived-copy",
      title: "保存派生副本",
      sourceStory: "同一事实同时存在源字段与副本。",
      syncStory: "每条更新路径都必须记得同步。",
      invalidStory: "副本可与源字段矛盾或过期。",
      designStory: "组件可以表示更多业务上无意义的状态。",
      conclusion: "重复 State 把正确性变成持续同步任务。",
    },
    {
      id: "derive-from-source",
      title: "保存最小事实并派生",
      sourceStory: "每个事实只有一个权威来源。",
      syncStory: "render 直接计算，不需要同步 Effect。",
      invalidStory: "stale derived copy 无法出现。",
      designStory: "状态空间更小，数据流更直接。",
      conclusion: "减少 State 往往是在删除错误状态，而不只是减少代码。",
    },
  ],
  misconceptions: {
    "derived-value-needs-state": {
      id: "derived-value-needs-state",
      title: "认为 UI 要显示的值都应该放进 State",
      diagnosis: "State 应保存独立事实；能由当前 props/state 完整得到的值属于 render-time derivation。",
      counterEvidence: "Demo 的 derivedFullName 始终跟随 firstName/lastName，而 storedFullName 可以因为漏同步而过期。",
      experiment: "点击“只改事实来源，故意漏同步”，比较 storedFullName 与 derivedFullName。",
      evidenceRefs: [{ kind: "source", fileName: "StateDryDemo.jsx", startLine: 45, endLine: 49 }],
    },
    "effect-fixes-duplicate-state": {
      id: "effect-fixes-duplicate-state",
      title: "认为用 Effect 同步副本就解决了重复 State",
      diagnosis: "Effect 只是增加一条运行时同步路径，并没有消除两个值表达同一事实的根因。",
      counterEvidence: "Demo 直接派生 fullName 不需要任何同步步骤，也不存在源与副本短暂或永久不一致。",
      experiment: "列出 firstName/lastName 改变后，为维持 storedFullName 正确必须额外发生的步骤。",
      evidenceRefs: [{ kind: "source", fileName: "StateDryDemo.jsx", startLine: 45, endLine: 49 }],
    },
    "copy-entity-is-selection": {
      id: "copy-entity-is-selection",
      title: "认为选择某个实体时保存完整对象副本更方便",
      diagnosis: "当 canonical collection 更新时，对象副本不会自动跟随；选择关系通常只需要保存稳定 id。",
      counterEvidence: "Demo 的 selectedCopy 会 stale，而 selectedId 每次都从最新 cartItems 派生 selectedItem。",
      experiment: "选择商品后修改数量，比较 selectedCopy 与 selectedItem。",
      evidenceRefs: [{ kind: "source", fileName: "StateDryDemo.jsx", startLine: 56, endLine: 63 }],
    },
    "booleans-are-always-simpler": {
      id: "booleans-are-always-simpler",
      title: "认为多个 boolean 总比一个 status 清楚",
      diagnosis: "当 boolean 共同描述互斥流程时，它们的笛卡尔组合会包含业务不允许的状态。",
      counterEvidence: "isSending && isSent 在 Demo 中可以同时为 true，而 status 只枚举 typing/sending/sent。",
      experiment: "同时勾选 isSending 与 isSent，再比较 status 能否表达同样的矛盾组合。",
      evidenceRefs: [{ kind: "source", fileName: "StateDryDemo.jsx", startLine: 51, endLine: 54 }],
    },
  },
};
