export const USE_EFFECT_CORRECT_USAGE_MODEL = {
  learningUnitId: "use-effect-correct-usage",
  version: 1,
  mechanismTitle: "Effect 把 committed React 状态同步到外部系统",
  mechanismAriaLabel: "useEffect 外部同步与 Cleanup 机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它负责什么",
    change: "依赖或挂载状态变化时",
  },
  contrastTitle: "Effect 的核心是 setup / cleanup 外部同步，不是“监听 State 后跑代码”",
  contrastDimensions: [
    { id: "causeStory", label: "为什么运行" },
    { id: "setupStory", label: "Setup" },
    { id: "cleanupStory", label: "Cleanup" },
    { id: "boundaryStory", label: "边界" },
  ],
  codeEvidence: [
    {
      id: "resize-subscription-cleanup",
      title: "Effect 建立 resize 订阅，并用同一 handler 对称清理",
      explanation: "setup 注册浏览器事件 listener；cleanup 移除同一个 listener。组件卸载或同步需要重建时，旧关系必须被撤销。",
      sourceRef: { kind: "source", fileName: "UseEffectCorrectUsageDemo.jsx", startLine: 3, endLine: 17 },
    },
    {
      id: "document-title-sync",
      title: "State 改变后 Effect 把 committed 值同步到 document.title",
      explanation: "按钮只更新 React State；Effect 使用最新 pageTitleBadge 更新 React 之外的 document.title，并在旧同步结束时恢复之前标题。",
      sourceRef: { kind: "source", fileName: "UseEffectCorrectUsageDemo.jsx", startLine: 56, endLine: 75 },
    },
  ],
  mechanismMap: [
    {
      id: "react-state",
      label: "Committed React state",
      example: "pageTitleBadge",
      role: "React 内部当前已提交事实。",
      change: "新 render/commit 后 Effect 可用新值重新同步。",
    },
    {
      id: "external-system",
      label: "External system",
      example: "window listener / document.title",
      role: "React 之外、需要与当前组件状态保持一致的系统。",
      change: "通过 Effect setup 更新或连接。",
    },
    {
      id: "setup",
      label: "Setup",
      example: "addEventListener / set title",
      role: "建立当前一轮外部同步。",
      change: "首次 commit 或依赖变化后运行。",
    },
    {
      id: "cleanup",
      label: "Cleanup",
      example: "removeEventListener / restore title",
      role: "撤销上一轮 setup 建立的外部关系。",
      change: "下一轮 setup 前或组件卸载时运行。",
    },
  ],
  contrastCases: [
    {
      id: "external-subscription",
      title: "外部订阅",
      causeStory: "组件存在时需要持续监听浏览器 resize。",
      setupStory: "注册 handler。",
      cleanupStory: "移除同一个 handler。",
      boundaryStory: "这是典型 Effect：组件生命周期内维护外部关系。",
      conclusion: "setup 建立什么，cleanup 就对称撤销什么。",
    },
    {
      id: "event-command",
      title: "一次用户命令",
      causeStory: "用户这次点击明确导致提交/购买/通知。",
      setupStory: "不需要靠 Effect 猜测事件。",
      cleanupStory: "通常没有“撤销外部订阅”的生命周期关系。",
      boundaryStory: "直接留在 Event Handler 更保留因果。",
      conclusion: "有副作用不代表都该放 Effect；先看为什么运行。",
    },
  ],
  misconceptions: {
    "effect-is-state-listener": {
      id: "effect-is-state-listener",
      title: "认为 Effect 就是通用的 State 变化监听器",
      diagnosis: "Effect 的判断标准是是否需要同步 React 外部系统，而不是某个 State 是否发生变化。",
      counterEvidence: "Demo 的 pageTitleBadge Effect 是因为 document.title 属于外部系统；仅仅派生显示值则不需要 Effect。",
      experiment: "把“计算 unread 文案”和“同步 document.title”分开：哪个离开 React 数据流？",
      evidenceRefs: [{ kind: "source", fileName: "UseEffectCorrectUsageDemo.jsx", startLine: 56, endLine: 75 }],
    },
    "cleanup-is-optional-for-subscription": {
      id: "cleanup-is-optional-for-subscription",
      title: "认为事件监听只 setup 不 cleanup 也没关系",
      diagnosis: "订阅会在组件离开或同步重建后继续存在，造成重复监听、泄漏或 stale handler。",
      counterEvidence: "Demo 的 resize setup 与 cleanup 使用同一个 handleResize 形成对称 add/remove。",
      experiment: "去掉 removeEventListener 后反复挂载 watcher，推演会留下多少 listener。",
      evidenceRefs: [{ kind: "source", fileName: "UseEffectCorrectUsageDemo.jsx", startLine: 3, endLine: 17 }],
    },
    "every-effect-needs-cleanup": {
      id: "every-effect-needs-cleanup",
      title: "认为每个 Effect 都必须机械返回 cleanup",
      diagnosis: "Cleanup 只在 setup 建立了需要停止、撤销或释放的外部关系时有意义；不是语法仪式。",
      counterEvidence: "关键问题是 setup 做了什么，而不是“看到 useEffect 就先 return”。",
      experiment: "分别判断“设置一次 analytics page view”和“注册 resize listener”是否存在可撤销资源。",
      evidenceRefs: [{ kind: "source", fileName: "UseEffectCorrectUsageDemo.jsx", startLine: 3, endLine: 17 }],
    },
    "event-command-needs-effect": {
      id: "event-command-needs-effect",
      title: "认为网络提交等副作用必须先 setState 再由 Effect 执行",
      diagnosis: "如果动作由这次明确用户交互导致，Event Handler 能直接表达因果；绕进 Effect 反而把原因隐藏成 State 变化。",
      counterEvidence: "本课边界说明 Effect 面向外部同步，不是所有业务命令的统一入口。",
      experiment: "比较“按钮点击立即 POST”与“组件存在期间订阅 socket”两者为什么运行。",
      evidenceRefs: [{ kind: "source", fileName: "UseEffectCorrectUsageDemo.jsx", startLine: 67, endLine: 75 }],
    },
  },
};
