export const USE_REF_MODEL = {
  learningUnitId: "use-ref",
  version: 1,
  mechanismTitle: "State 驱动 render；Ref 保存不会驱动 UI 的可变信息",
  mechanismAriaLabel: "useRef 与 State 职责机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它负责什么",
    change: "写入时",
  },
  contrastTitle: "Ref 的可变性不等于它适合成为 UI 的事实来源",
  contrastDimensions: [
    { id: "lifetimeStory", label: "生命周期" },
    { id: "renderStory", label: "Render" },
    { id: "uiStory", label: "UI" },
    { id: "accessStory", label: "访问时机" },
  ],
  codeEvidence: [
    {
      id: "dom-ref-event-access",
      title: "事件处理器在 commit 后通过 DOM ref 执行 focus",
      explanation: "inputRef.current 指向已经提交的 input DOM。点击或发送事件里调用 focus 是命令式 DOM 交互，不需要把节点本身放进 State。",
      sourceRef: { kind: "source", fileName: "UseRefDemo.jsx", startLine: 31, endLine: 42 },
    },
    {
      id: "timer-handle-vs-visible-state",
      title: "计时器句柄放 Ref，可见秒数仍由 State 驱动",
      explanation: "timerIdRef.current 只保存跨 render 的 interval handle；写入它不会请求 render。屏幕上的 timerSeconds 和 isTimerRunning 仍然使用 State。",
      sourceRef: { kind: "source", fileName: "UseRefDemo.jsx", startLine: 47, endLine: 66 },
    },
  ],
  mechanismMap: [
    {
      id: "state",
      label: "State",
      example: "timerSeconds",
      role: "当前 render 的声明式输入，变化需要反映到 JSX。",
      change: "setter 请求新的 render。",
    },
    {
      id: "ref-object",
      label: "Ref object",
      example: "timerIdRef",
      role: "组件实例内稳定的可变容器。",
      change: "写 .current 不会请求 render。",
    },
    {
      id: "dom-ref",
      label: "DOM ref",
      example: "inputRef.current",
      role: "commit 后指向真实 DOM 节点，用于 focus/scroll/measure 等命令式交互。",
      change: "节点挂载/卸载时 React 更新 current。",
    },
    {
      id: "render-boundary",
      label: "Render boundary",
      example: "ref.current",
      role: "通常不应作为 render-time 可变事实来源。",
      change: "普通 render 中读写可变 ref 会降低纯计算可预测性。",
    },
  ],
  contrastCases: [
    {
      id: "visible-value-in-state",
      title: "可见值放 State",
      lifetimeStory: "跨 render 保留当前值。",
      renderStory: "更新通过 setter 进入 React 调度。",
      uiStory: "下一次 render 用新值重新计算 JSX。",
      accessStory: "render 中可以安全读取当前 snapshot。",
      conclusion: "只要变化必须立即反映 UI，State 才是声明式事实来源。",
    },
    {
      id: "imperative-handle-in-ref",
      title: "命令式句柄放 Ref",
      lifetimeStory: "同一个 ref 对象跨 render 保留。",
      renderStory: "写 current 不会触发 render。",
      uiStory: "handle 本身不直接决定 JSX。",
      accessStory: "在事件或合适 Effect 中读写；DOM ref 要等对应节点 commit。",
      conclusion: "Ref 适合“需要记住，但不需要驱动 UI”的值。",
    },
  ],
  misconceptions: {
    "ref-drives-ui": {
      id: "ref-drives-ui",
      title: "认为把可见值放 ref.current 就能自动更新界面",
      diagnosis: "React 不会因为 ref.current 改变而重新 render；JSX 继续显示上一次 render 的结果。",
      counterEvidence: "Demo 的 timerId 放 Ref，但可见秒数仍使用 timerSeconds State。",
      experiment: "设想把 timerSeconds 也改成 ref.current++：没有其他 render 时，屏幕数字为什么不会自动变化？",
      evidenceRefs: [{ kind: "source", fileName: "UseRefDemo.jsx", startLine: 47, endLine: 66 }],
    },
    "ref-write-rerenders": {
      id: "ref-write-rerenders",
      title: "认为写 ref.current 等价于 setState",
      diagnosis: "Ref 是静默可变容器；React 不追踪 current 的写入来安排 render。",
      counterEvidence: "startTimer / stopTimer 写 timerIdRef.current，同时需要单独 setIsTimerRunning 来更新 UI。",
      experiment: "对比 timerIdRef.current = ... 与 setIsTimerRunning(true) 各自是否进入 React render 调度。",
      evidenceRefs: [{ kind: "source", fileName: "UseRefDemo.jsx", startLine: 52, endLine: 66 }],
    },
    "dom-ref-during-render": {
      id: "dom-ref-during-render",
      title: "认为 render 时就可以依赖 DOM ref.current 做 UI 计算",
      diagnosis: "DOM ref 要到 commit 后才指向真实节点；普通 render-time ref 读写也会破坏声明式纯计算边界。",
      counterEvidence: "Demo 的 focus 发生在事件处理器中，scroll 发生在 layout effect 中，而不是组件函数计算 JSX 时。",
      experiment: "指出 inputRef.current 何时才可能指向已提交 DOM，并解释初次 render 时为什么不能依赖它。",
      evidenceRefs: [
        { kind: "source", fileName: "UseRefDemo.jsx", startLine: 17, endLine: 29 },
        { kind: "source", fileName: "UseRefDemo.jsx", startLine: 31, endLine: 42 },
      ],
    },
    "ref-is-better-state": {
      id: "ref-is-better-state",
      title: "认为 Ref 因为不触发 render，所以比 State 更适合保存所有数据",
      diagnosis: "不触发 render 只有在这个值不应驱动 UI 时才是优点；可见业务状态藏进 Ref 会制造 stale UI。",
      counterEvidence: "Demo 明确把 interval handle 与可见 seconds/running status 分开。",
      experiment: "把每个值按“改变后是否必须反映到 JSX”分类，再决定 State 或 Ref。",
      evidenceRefs: [{ kind: "source", fileName: "UseRefDemo.jsx", startLine: 47, endLine: 66 }],
    },
  },
};
