export const USE_REDUCE_WITH_CONTEXT_MODEL = {
  learningUnitId: "use-reduce-with-context",
  version: 1,
  mechanismTitle: "Reducer 管转换，Context 管分发；State 与 Dispatch 可以拥有不同订阅边界",
  mechanismAriaLabel: "Reducer Context 双通道机制区分",
  mechanismHeaders: {
    subject: "对象",
    example: "当前 Demo",
    role: "它负责什么",
    change: "tasks 更新时",
  },
  contrastTitle: "dispatch-only consumer 是否需要订阅整份 State",
  contrastDimensions: [
    { id: "valueStory", label: "Provider value" },
    { id: "consumerStory", label: "写组件读取" },
    { id: "subscriptionStory", label: "订阅面" },
    { id: "updateStory", label: "tasks 改变" },
  ],
  codeEvidence: [
    {
      id: "split-providers",
      title: "State Context 与 Dispatch Context 分开提供",
      explanation: "TaskProvider 把 tasks 与稳定 dispatch 放进两条 Context；只需要 dispatch 的组件不必读取 State Context。",
      sourceRef: { kind: "source", fileName: "UseReduceWithContextDemo.jsx", startLine: 38, endLine: 45 },
    },
    {
      id: "single-object-provider",
      title: "单 Context 把 { tasks, dispatch } 组合成一个 value",
      explanation: "tasks 每次变化都会生成新的对象 value；为了拿 dispatch 而读取 SingleTaskContext 的写组件也订阅了这份变化。",
      sourceRef: { kind: "source", fileName: "UseReduceWithContextDemo.jsx", startLine: 48, endLine: 62 },
    },
  ],
  mechanismMap: [
    {
      id: "reducer",
      label: "Reducer",
      example: "taskReducer",
      role: "集中计算任务状态转换。",
      change: "与 Context 是否拆分是不同职责。",
    },
    {
      id: "state-context",
      label: "State Context",
      example: "TaskStateContext",
      role: "向真正读取 tasks 的组件分发当前 State。",
      change: "tasks 变化时消费者收到新值。",
    },
    {
      id: "dispatch-context",
      label: "Dispatch Context",
      example: "TaskDispatchContext",
      role: "向只需发 action 的组件分发稳定 dispatch。",
      change: "tasks 改变不等于这条 Context value 改变。",
    },
    {
      id: "consumer-boundary",
      label: "Consumer boundary",
      example: "AddButton / TaskList",
      role: "按真实依赖选择读取 State、Dispatch 或两者。",
      change: "订阅面由读取哪条 Context 决定。",
    },
  ],
  contrastCases: [
    {
      id: "single-context",
      title: "单 Context：{ tasks, dispatch }",
      valueStory: "tasks 变化生成新的对象 identity。",
      consumerStory: "AddButton 为取 dispatch 也读取整个对象。",
      subscriptionStory: "写组件与读组件都订阅同一 value。",
      updateStory: "tasks 变化会通知 dispatch-only consumer。",
      conclusion: "依赖边界被一个组合对象绑在一起。",
    },
    {
      id: "split-context",
      title: "双 Context：State / Dispatch",
      valueStory: "tasks 与稳定 dispatch 分开提供。",
      consumerStory: "AddButton 只读取 Dispatch Context。",
      subscriptionStory: "写组件不订阅 State Context。",
      updateStory: "tasks 变化不会通过 State Context 通知 AddButton。",
      conclusion: "拆分优化的是 Context 订阅面，不是保证组件永远不 render。",
    },
  ],
  misconceptions: {
    "single-context-is-free": {
      id: "single-context-is-free",
      title: "认为把 state + dispatch 放一个 Context 对 dispatch-only consumer 没影响",
      diagnosis: "为了取 dispatch，组件也订阅了整个对象 value；state 改变会产生新 value identity。",
      counterEvidence: "Demo 的 SingleTaskContext value={{ tasks, dispatch }} 与 AddButton 都读取同一 Context。",
      experiment: "比较单 Context 与双 Context 的 dispatch-only 探针在 tasks 更新后的变化。",
      evidenceRefs: [
        { kind: "source", fileName: "UseReduceWithContextDemo.jsx", startLine: 48, endLine: 62 },
      ],
    },
    "split-context-prevents-all-renders": {
      id: "split-context-prevents-all-renders",
      title: "认为拆 State/Dispatch Context 可以保证写组件永不重新 render",
      diagnosis: "它只移除 State Context 这一个通知来源；props、自身 State、其他 Context、父级结构仍可能让组件更新。",
      counterEvidence: "Demo 明确把拆分描述为 subscription boundary，而不是 render guarantee。",
      experiment: "给 AddButton 增加一个变化的 prop，说明即使不订阅 State Context 也仍可能 render。",
      evidenceRefs: [{ kind: "source", fileName: "UseReduceWithContextDemo.jsx", startLine: 58, endLine: 62 }],
    },
    "reducer-and-context-same-job": {
      id: "reducer-and-context-same-job",
      title: "认为 useReducer 自动提供跨组件共享",
      diagnosis: "Reducer 只组织状态转换；Context 才负责把 state/dispatch 跨层分发。",
      counterEvidence: "TaskProvider 显式把 useReducer 返回值分别提供给 Context。",
      experiment: "移除 Provider，只保留 useReducer，判断深层 AddButton 如何获得 dispatch。",
      evidenceRefs: [{ kind: "source", fileName: "UseReduceWithContextDemo.jsx", startLine: 38, endLine: 45 }],
    },
  },
};
